"""
Dados dos Anexos do Edital nº 4/2025 - TJPR
Atualizado com secretarias de direção de fórum
"""

# =============================================================================
# ANEXO I - Vagas com déficit
# Formato: "CODIGO": {"comarca": "...", "unidade": "...", "quantidade": N}
# =============================================================================

ANEXO_I = {
    "A1-001": {"comarca": "Almirante Tamandaré", "unidade": "1ª VARA CRIMINAL", "quantidade": 1},
    "A1-002": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS E DA FAZENDA PÚBLICA", "quantidade": 3},
    "A1-003": {"comarca": "Alto Paraná", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-004": {"comarca": "Alto Piquiri", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-005": {"comarca": "Altônia", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-006": {"comarca": "Ampére", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-007": {"comarca": "Andirá", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-008": {"comarca": "Antonina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-009": {"comarca": "Arapongas", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-010": {"comarca": "Arapongas", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-011": {"comarca": "Arapongas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-012": {"comarca": "Arapongas", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-013": {"comarca": "Araucária", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-014": {"comarca": "Araucária", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-015": {"comarca": "Assaí", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-016": {"comarca": "Assis Chateaubriand", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-017": {"comarca": "Barbosa Ferraz", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-018": {"comarca": "Barracão", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-019": {"comarca": "Bela Vista do Paraíso", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-020": {"comarca": "Bocaiúva do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-021": {"comarca": "Cambará", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-022": {"comarca": "Campina da Lagoa", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-023": {"comarca": "Campina Grande do Sul", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-024": {"comarca": "Campina Grande do Sul", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA E DA INFÂNCIA E JUVENTUDE", "quantidade": 1},
    "A1-025": {"comarca": "Campo Largo", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-026": {"comarca": "Campo Largo", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-027": {"comarca": "Campo Largo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-028": {"comarca": "Campo Largo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-029": {"comarca": "Campo Mourão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-030": {"comarca": "Cândido de Abreu", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-031": {"comarca": "Capanema", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-032": {"comarca": "Capitão Leônidas Marques", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-033": {"comarca": "Cascavel", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 2},
    "A1-034": {"comarca": "Cascavel", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO", "quantidade": 1},
    "A1-035": {"comarca": "Cascavel", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 3},
    "A1-036": {"comarca": "Cascavel", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 3},
    "A1-037": {"comarca": "Cascavel", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-038": {"comarca": "Cascavel", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-039": {"comarca": "Castro", "unidade": "VARA CRIMINAL", "quantidade": 6},
    "A1-040": {"comarca": "Castro", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-041": {"comarca": "Castro", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-042": {"comarca": "Catanduvas", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-043": {"comarca": "Chopinzinho", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-044": {"comarca": "Cianorte", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-045": {"comarca": "Cianorte", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-046": {"comarca": "Cidade Gaúcha", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-047": {"comarca": "Clevelândia", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-048": {"comarca": "Colombo", "unidade": "2ª VARA CÍVEL", "quantidade": 1},
    "A1-049": {"comarca": "Colombo", "unidade": "1ª VARA CRIMINAL", "quantidade": 3},
    "A1-050": {"comarca": "Colombo", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-051": {"comarca": "Colombo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-052": {"comarca": "Colombo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 3},
    "A1-053": {"comarca": "Colombo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-054": {"comarca": "Colombo", "unidade": "VARA DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-055": {"comarca": "Colorado", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-056": {"comarca": "Congonhinhas", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-057": {"comarca": "Corbélia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-058": {"comarca": "Cornélio Procópio", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-059": {"comarca": "Coronel Vivida", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-060": {"comarca": "Curitiba", "unidade": "18ª VARA CÍVEL", "quantidade": 1},
    "A1-061": {"comarca": "Curitiba", "unidade": "24ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-062": {"comarca": "Curitiba", "unidade": "25ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-063": {"comarca": "Curitiba", "unidade": "26ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-064": {"comarca": "Curitiba", "unidade": "27ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-065": {"comarca": "Curitiba", "unidade": "VARA DA INFÂNCIA E DA JUVENTUDE E ADOÇÃO", "quantidade": 1},
    "A1-066": {"comarca": "Curitiba", "unidade": "VARA DE ADOLESCENTES EM CONFLITO COM A LEI", "quantidade": 1},
    "A1-067": {"comarca": "Curitiba", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-068": {"comarca": "Curitiba", "unidade": "CENTRAL DE GARANTIAS ESPECIALIZADA", "quantidade": 2},
    "A1-069": {"comarca": "Curitiba", "unidade": "1ª VARA DESCENTRALIZADA DO PINHEIRINHO", "quantidade": 2},
    "A1-070": {"comarca": "Curitiba", "unidade": "9ª VARA CRIMINAL", "quantidade": 1},
    "A1-071": {"comarca": "Curitiba", "unidade": "10ª VARA CRIMINAL", "quantidade": 1},
    "A1-072": {"comarca": "Curitiba", "unidade": "13ª VARA CRIMINAL", "quantidade": 1},
    "A1-073": {"comarca": "Curitiba", "unidade": "1ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI", "quantidade": 1},
    "A1-074": {"comarca": "Curitiba", "unidade": "3º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER - CASA DA MULHER BRASILEIRA", "quantidade": 1},
    "A1-075": {"comarca": "Curitiba", "unidade": "1ª VARA DESCENTRALIZADA DO BAIRRO NOVO (SÍTIO CERCADO)", "quantidade": 2},
    "A1-076": {"comarca": "Curitiba", "unidade": "1ª VARA DESCENTRALIZADA DO BOQUEIRÃO", "quantidade": 1},
    "A1-077": {"comarca": "Curitiba", "unidade": "11º JUIZADO ESPECIAL CÍVEL E CRIMINAL", "quantidade": 1},
    "A1-078": {"comarca": "Curitiba", "unidade": "1ª VARA DESCENTRALIZADA DE SANTA FELICIDADE", "quantidade": 2},
    "A1-079": {"comarca": "Curitiba", "unidade": "13º JUIZADO ESPECIAL CÍVEL E CRIMINAL", "quantidade": 1},
    "A1-080": {"comarca": "Curitiba", "unidade": "1ª VARA DESCENTRALIZADA DA CIDADE INDUSTRIAL", "quantidade": 1},
    "A1-081": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-082": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS ESPECIAIS DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-083": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS ESTADUAIS", "quantidade": 3},
    "A1-084": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS MUNICIPAIS", "quantidade": 2},
    "A1-085": {"comarca": "Curiúva", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-086": {"comarca": "Dois Vizinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 4},
    "A1-087": {"comarca": "Engenheiro Beltrão", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-088": {"comarca": "Faxinal", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-089": {"comarca": "Fazenda Rio Grande", "unidade": "VARA CRIMINAL", "quantidade": 5},
    "A1-090": {"comarca": "Fazenda Rio Grande", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 3},
    "A1-091": {"comarca": "Fazenda Rio Grande", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-092": {"comarca": "Fazenda Rio Grande", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-093": {"comarca": "Formosa do Oeste", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-094": {"comarca": "Foz do Iguaçu", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-095": {"comarca": "Foz do Iguaçu", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-096": {"comarca": "Foz do Iguaçu", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 2},
    "A1-097": {"comarca": "Foz do Iguaçu", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-098": {"comarca": "Francisco Beltrão", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-099": {"comarca": "Francisco Beltrão", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-100": {"comarca": "Francisco Beltrão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-101": {"comarca": "Grandes Rios", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-102": {"comarca": "Guaíra", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-103": {"comarca": "Guaraniaçu", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-104": {"comarca": "Guarapuava", "unidade": "1ª VARA CRIMINAL", "quantidade": 1},
    "A1-105": {"comarca": "Guaratuba", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-106": {"comarca": "Ibaiti", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-107": {"comarca": "Ibiporã", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-108": {"comarca": "Icaraíma", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-109": {"comarca": "Imbituva", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-110": {"comarca": "Iporã", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-111": {"comarca": "Irati", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-112": {"comarca": "Irati", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS", "quantidade": 3},
    "A1-113": {"comarca": "Iretama", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-114": {"comarca": "Ivaiporã", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-115": {"comarca": "Jacarezinho", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-116": {"comarca": "Jaguapitã", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-117": {"comarca": "Jaguariaíva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-118": {"comarca": "Joaquim Távora", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-119": {"comarca": "Laranjeiras do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-120": {"comarca": "Loanda", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-121": {"comarca": "Londrina", "unidade": "3ª VARA DE FAMÍLIA", "quantidade": 1},
    "A1-122": {"comarca": "Londrina", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 1},
    "A1-123": {"comarca": "Londrina", "unidade": "VARA DE SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-124": {"comarca": "Londrina", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 6},
    "A1-125": {"comarca": "Mamborê", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-126": {"comarca": "Mandaguaçu", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-127": {"comarca": "Mangueirinha", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-128": {"comarca": "Manoel Ribas", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-129": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-130": {"comarca": "Marilândia do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-131": {"comarca": "Maringá", "unidade": "3ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-132": {"comarca": "Maringá", "unidade": "7ª VARA CÍVEL", "quantidade": 1},
    "A1-133": {"comarca": "Maringá", "unidade": "1ª VARA CRIMINAL", "quantidade": 1},
    "A1-134": {"comarca": "Maringá", "unidade": "3ª VARA CRIMINAL", "quantidade": 1},
    "A1-135": {"comarca": "Maringá", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO", "quantidade": 1},
    "A1-136": {"comarca": "Maringá", "unidade": "1ª VARA DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-137": {"comarca": "Maringá", "unidade": "2ª VARA DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-138": {"comarca": "Marmeleiro", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-139": {"comarca": "Matelândia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-140": {"comarca": "Matinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-141": {"comarca": "Medianeira", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 5},
    "A1-142": {"comarca": "Morretes", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-143": {"comarca": "Nova Aurora", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-144": {"comarca": "Nova Esperança", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-145": {"comarca": "Nova Esperança", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-146": {"comarca": "Nova Fátima", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-147": {"comarca": "Ortigueira", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-148": {"comarca": "Paiçandu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-149": {"comarca": "Paiçandu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-150": {"comarca": "Palmas", "unidade": "VARA CRIMINAL E DA INFÂNCIA E JUVENTUDE", "quantidade": 3},
    "A1-151": {"comarca": "Palmas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-152": {"comarca": "Palmeira", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-153": {"comarca": "Palotina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-154": {"comarca": "Paraíso do Norte", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-155": {"comarca": "Paranacity", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-156": {"comarca": "Paranaguá", "unidade": "1ª VARA CÍVEL", "quantidade": 2},
    "A1-157": {"comarca": "Paranaguá", "unidade": "2ª VARA CÍVEL", "quantidade": 4},
    "A1-158": {"comarca": "Paranaguá", "unidade": "VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 2},
    "A1-159": {"comarca": "Paranaguá", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-160": {"comarca": "Paranaguá", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-161": {"comarca": "Pato Branco", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-162": {"comarca": "Peabiru", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-163": {"comarca": "Pérola", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-164": {"comarca": "Pinhais", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-165": {"comarca": "Pinhão", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-166": {"comarca": "Pinhão", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-167": {"comarca": "Piraí do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-168": {"comarca": "Piraquara", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 4},
    "A1-169": {"comarca": "Piraquara", "unidade": "VARA CRIMINAL", "quantidade": 4},
    "A1-170": {"comarca": "Piraquara", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-171": {"comarca": "Pitanga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-172": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 2},
    "A1-173": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-174": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-175": {"comarca": "Ponta Grossa", "unidade": "3ª VARA CRIMINAL", "quantidade": 2},
    "A1-176": {"comarca": "Ponta Grossa", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 3},
    "A1-177": {"comarca": "Ponta Grossa", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-178": {"comarca": "Ponta Grossa", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 1},
    "A1-179": {"comarca": "Pontal do Paraná", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-180": {"comarca": "Porecatu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-181": {"comarca": "Primeiro de Maio", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-182": {"comarca": "Quatro Barras", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-183": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-184": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-185": {"comarca": "Realeza", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-186": {"comarca": "Rebouças", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-187": {"comarca": "Reserva", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-188": {"comarca": "Ribeirão Claro", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-189": {"comarca": "Ribeirão do Pinhal", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-190": {"comarca": "Rio Branco do Sul", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE", "quantidade": 1},
    "A1-191": {"comarca": "Salto do Lontra", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-192": {"comarca": "Santa Fé", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-193": {"comarca": "Santa Helena", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-194": {"comarca": "Santa Isabel do Ivaí", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-195": {"comarca": "Santo Antônio da Platina", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-196": {"comarca": "Santo Antônio da Platina", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-197": {"comarca": "Santo Antônio do Sudoeste", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-198": {"comarca": "São Jerônimo da Serra", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-199": {"comarca": "São João", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-200": {"comarca": "São João do Triunfo", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-201": {"comarca": "São José dos Pinhais", "unidade": "3ª VARA CÍVEL", "quantidade": 2},
    "A1-202": {"comarca": "São José dos Pinhais", "unidade": "2ª VARA CRIMINAL", "quantidade": 1},
    "A1-203": {"comarca": "São José dos Pinhais", "unidade": "VARA DESCENTRALIZADA DO AFONSO PENA", "quantidade": 1},
    "A1-204": {"comarca": "São José dos Pinhais", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-205": {"comarca": "São Mateus do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-206": {"comarca": "São Miguel do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-207": {"comarca": "Siqueira Campos", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-208": {"comarca": "Teixeira Soares", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-209": {"comarca": "Telêmaco Borba", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-210": {"comarca": "Telêmaco Borba", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-211": {"comarca": "Telêmaco Borba", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-212": {"comarca": "Telêmaco Borba", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-213": {"comarca": "Terra Rica", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-214": {"comarca": "Terra Roxa", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-215": {"comarca": "Tibagi", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-216": {"comarca": "Toledo", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-217": {"comarca": "Toledo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-218": {"comarca": "Tomazina", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-219": {"comarca": "Ubiratã", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-220": {"comarca": "Umuarama", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-221": {"comarca": "Umuarama", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-222": {"comarca": "União da Vitória", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-223": {"comarca": "União da Vitória", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-224": {"comarca": "Wenceslau Braz", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-225": {"comarca": "Cambé", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
}

# =============================================================================
# ANEXO II - Todas as unidades (incluindo secretarias de direção de fórum)
# Formato: "CODIGO": {"comarca": "...", "unidade": "..."}
# =============================================================================

ANEXO_II = {
    "A2-001": {"comarca": "Almirante Tamandaré", "unidade": "1ª VARA CRIMINAL"},
    "A2-002": {"comarca": "Almirante Tamandaré", "unidade": "2ª VARA CRIMINAL"},
    "A2-003": {"comarca": "Almirante Tamandaré", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-004": {"comarca": "Almirante Tamandaré", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-005": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS E DA FAZENDA PÚBLICA"},
    "A2-006": {"comarca": "Alto Paraná", "unidade": "JUÍZO ÚNICO"},
    "A2-007": {"comarca": "Alto Piquiri", "unidade": "JUÍZO ÚNICO"},
    "A2-008": {"comarca": "Altônia", "unidade": "JUÍZO ÚNICO"},
    "A2-009": {"comarca": "Ampére", "unidade": "JUÍZO ÚNICO"},
    "A2-010": {"comarca": "Andirá", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-011": {"comarca": "Antonina", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-012": {"comarca": "Antonina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-013": {"comarca": "Apucarana", "unidade": "1ª VARA CRIMINAL"},
    "A2-014": {"comarca": "Apucarana", "unidade": "2ª VARA CRIMINAL"},
    "A2-015": {"comarca": "Apucarana", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-016": {"comarca": "Apucarana", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-017": {"comarca": "Arapongas", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-018": {"comarca": "Arapongas", "unidade": "1ª VARA CRIMINAL"},
    "A2-019": {"comarca": "Arapongas", "unidade": "2ª VARA CRIMINAL"},
    "A2-020": {"comarca": "Arapongas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-021": {"comarca": "Arapongas", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-022": {"comarca": "Arapoti", "unidade": "JUÍZO ÚNICO"},
    "A2-023": {"comarca": "Araucária", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-024": {"comarca": "Araucária", "unidade": "VARA CRIMINAL"},
    "A2-025": {"comarca": "Araucária", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-026": {"comarca": "Araucária", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-027": {"comarca": "Assaí", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-028": {"comarca": "Assis Chateaubriand", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-029": {"comarca": "Astorga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-030": {"comarca": "Bandeirantes", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-031": {"comarca": "Bandeirantes", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-032": {"comarca": "Barbosa Ferraz", "unidade": "JUÍZO ÚNICO"},
    "A2-033": {"comarca": "Barracão", "unidade": "JUÍZO ÚNICO"},
    "A2-034": {"comarca": "Bela Vista do Paraíso", "unidade": "JUÍZO ÚNICO"},
    "A2-035": {"comarca": "Bocaiúva do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-036": {"comarca": "Cambará", "unidade": "JUÍZO ÚNICO"},
    "A2-037": {"comarca": "Cambé", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-038": {"comarca": "Cambé", "unidade": "VARA CRIMINAL"},
    "A2-039": {"comarca": "Cambé", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-040": {"comarca": "Cambé", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-041": {"comarca": "Campina da Lagoa", "unidade": "JUÍZO ÚNICO"},
    "A2-042": {"comarca": "Campina Grande do Sul", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-043": {"comarca": "Campina Grande do Sul", "unidade": "VARA CRIMINAL"},
    "A2-044": {"comarca": "Campina Grande do Sul", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA E DA INFÂNCIA E JUVENTUDE"},
    "A2-045": {"comarca": "Campo Largo", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-046": {"comarca": "Campo Largo", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-047": {"comarca": "Campo Largo", "unidade": "VARA CRIMINAL"},
    "A2-048": {"comarca": "Campo Largo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-049": {"comarca": "Campo Largo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-050": {"comarca": "Campo Mourão", "unidade": "1ª VARA CRIMINAL"},
    "A2-051": {"comarca": "Campo Mourão", "unidade": "2ª VARA CRIMINAL"},
    "A2-052": {"comarca": "Campo Mourão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-053": {"comarca": "Campo Mourão", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-054": {"comarca": "Cândido de Abreu", "unidade": "JUÍZO ÚNICO"},
    "A2-055": {"comarca": "Cantagalo", "unidade": "JUÍZO ÚNICO"},
    "A2-056": {"comarca": "Capanema", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-057": {"comarca": "Capitão Leônidas Marques", "unidade": "JUÍZO ÚNICO"},
    "A2-058": {"comarca": "Carlópolis", "unidade": "JUÍZO ÚNICO"},
    "A2-059": {"comarca": "Cascavel", "unidade": "4ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-060": {"comarca": "Cascavel", "unidade": "5ª VARA CÍVEL"},
    "A2-061": {"comarca": "Cascavel", "unidade": "1ª VARA CRIMINAL"},
    "A2-062": {"comarca": "Cascavel", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-063": {"comarca": "Cascavel", "unidade": "3ª VARA CRIMINAL"},
    "A2-064": {"comarca": "Cascavel", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-065": {"comarca": "Cascavel", "unidade": "1ª VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-066": {"comarca": "Cascavel", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-067": {"comarca": "Cascavel", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-068": {"comarca": "Cascavel", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-069": {"comarca": "Cascavel", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-070": {"comarca": "Cascavel", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-071": {"comarca": "Cascavel", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-072": {"comarca": "Cascavel", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-073": {"comarca": "Cascavel", "unidade": "4ª VARA CRIMINAL"},
    "A2-074": {"comarca": "Castro", "unidade": "VARA CRIMINAL"},
    "A2-075": {"comarca": "Castro", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-076": {"comarca": "Castro", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-077": {"comarca": "Catanduvas", "unidade": "JUÍZO ÚNICO"},
    "A2-078": {"comarca": "Centenário do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-079": {"comarca": "Cerro Azul", "unidade": "JUÍZO ÚNICO"},
    "A2-080": {"comarca": "Chopinzinho", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-081": {"comarca": "Cianorte", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-082": {"comarca": "Cianorte", "unidade": "VARA CRIMINAL"},
    "A2-083": {"comarca": "Cianorte", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-084": {"comarca": "Cianorte", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-085": {"comarca": "Cidade Gaúcha", "unidade": "JUÍZO ÚNICO"},
    "A2-086": {"comarca": "Clevelândia", "unidade": "JUÍZO ÚNICO"},
    "A2-087": {"comarca": "Colombo", "unidade": "2ª VARA CÍVEL"},
    "A2-088": {"comarca": "Colombo", "unidade": "1ª VARA CRIMINAL"},
    "A2-089": {"comarca": "Colombo", "unidade": "2ª VARA CRIMINAL"},
    "A2-090": {"comarca": "Colombo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-091": {"comarca": "Colombo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-092": {"comarca": "Colombo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-093": {"comarca": "Colombo", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-094": {"comarca": "Colorado", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-095": {"comarca": "Congonhinhas", "unidade": "JUÍZO ÚNICO"},
    "A2-096": {"comarca": "Corbélia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-097": {"comarca": "Cornélio Procópio", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-098": {"comarca": "Cornélio Procópio", "unidade": "VARA CRIMINAL"},
    "A2-099": {"comarca": "Cornélio Procópio", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-100": {"comarca": "Cornélio Procópio", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-101": {"comarca": "Coronel Vivida", "unidade": "JUÍZO ÚNICO"},
    "A2-102": {"comarca": "Cruzeiro do Oeste", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-103": {"comarca": "Cruzeiro do Oeste", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-104": {"comarca": "Curitiba", "unidade": "3ª VARA CÍVEL"},
    "A2-105": {"comarca": "Curitiba", "unidade": "10ª VARA CÍVEL"},
    "A2-106": {"comarca": "Curitiba", "unidade": "12ª VARA CÍVEL"},
    "A2-107": {"comarca": "Curitiba", "unidade": "15ª VARA CÍVEL"},
    "A2-108": {"comarca": "Curitiba", "unidade": "18ª VARA CÍVEL"},
    "A2-109": {"comarca": "Curitiba", "unidade": "23ª VARA CÍVEL"},
    "A2-110": {"comarca": "Curitiba", "unidade": "24ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-111": {"comarca": "Curitiba", "unidade": "25ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-112": {"comarca": "Curitiba", "unidade": "26ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-113": {"comarca": "Curitiba", "unidade": "27ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-114": {"comarca": "Curitiba", "unidade": "1ª VARA DE FAMÍLIA"},
    "A2-115": {"comarca": "Curitiba", "unidade": "3ª VARA DE FAMÍLIA"},
    "A2-116": {"comarca": "Curitiba", "unidade": "5ª VARA DE FAMÍLIA"},
    "A2-117": {"comarca": "Curitiba", "unidade": "6ª VARA DE FAMÍLIA"},
    "A2-118": {"comarca": "Curitiba", "unidade": "7ª VARA DE FAMÍLIA"},
    "A2-119": {"comarca": "Curitiba", "unidade": "1ª VARA DE SUCESSÕES"},
    "A2-120": {"comarca": "Curitiba", "unidade": "VARA DE REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-121": {"comarca": "Curitiba", "unidade": "VARA DA INFÂNCIA E DA JUVENTUDE E ADOÇÃO"},
    "A2-122": {"comarca": "Curitiba", "unidade": "2ª VARA DE SUCESSÕES"},
    "A2-123": {"comarca": "Curitiba", "unidade": "VARA DE ADOLESCENTES EM CONFLITO COM A LEI"},
    "A2-124": {"comarca": "Curitiba", "unidade": "1ª VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-125": {"comarca": "Curitiba", "unidade": "1ª VARA CRIMINAL"},
    "A2-126": {"comarca": "Curitiba", "unidade": "2ª VARA CRIMINAL"},
    "A2-127": {"comarca": "Curitiba", "unidade": "3ª VARA CRIMINAL"},
    "A2-128": {"comarca": "Curitiba", "unidade": "4ª VARA CRIMINAL"},
    "A2-129": {"comarca": "Curitiba", "unidade": "CENTRAL DE GARANTIAS ESPECIALIZADA"},
    "A2-130": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO PINHEIRINHO"},
    "A2-131": {"comarca": "Curitiba", "unidade": "7ª VARA CRIMINAL"},
    "A2-132": {"comarca": "Curitiba", "unidade": "8ª VARA CRIMINAL"},
    "A2-133": {"comarca": "Curitiba", "unidade": "9ª VARA CRIMINAL"},
    "A2-134": {"comarca": "Curitiba", "unidade": "10ª VARA CRIMINAL"},
    "A2-135": {"comarca": "Curitiba", "unidade": "2ª VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-136": {"comarca": "Curitiba", "unidade": "12ª VARA CRIMINAL"},
    "A2-137": {"comarca": "Curitiba", "unidade": "13ª VARA CRIMINAL"},
    "A2-138": {"comarca": "Curitiba", "unidade": "1ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI"},
    "A2-139": {"comarca": "Curitiba", "unidade": "2ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI"},
    "A2-140": {"comarca": "Curitiba", "unidade": "VARA DE DELITOS DE TRÂNSITO"},
    "A2-141": {"comarca": "Curitiba", "unidade": "3º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER - CASA DA MULHER BRASILEIRA"},
    "A2-142": {"comarca": "Curitiba", "unidade": "VARA DA AUDITORIA DA JUSTIÇA MILITAR"},
    "A2-143": {"comarca": "Curitiba", "unidade": "1º JUIZADO ESPECIAL CÍVEL - MATÉRIA BANCÁRIA"},
    "A2-144": {"comarca": "Curitiba", "unidade": "JUIZADO ESPECIAL PUC-CAJURU"},
    "A2-145": {"comarca": "Curitiba", "unidade": "3º JUIZADO ESPECIAL CÍVEL - TELECOMUNICAÇÕES"},
    "A2-146": {"comarca": "Curitiba", "unidade": "5º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-147": {"comarca": "Curitiba", "unidade": "6º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-148": {"comarca": "Curitiba", "unidade": "8º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-149": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO BAIRRO NOVO (SÍTIO CERCADO)"},
    "A2-150": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO BOQUEIRÃO"},
    "A2-151": {"comarca": "Curitiba", "unidade": "11º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-152": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DE SANTA FELICIDADE"},
    "A2-153": {"comarca": "Curitiba", "unidade": "13º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-154": {"comarca": "Curitiba", "unidade": "14º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-155": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DA CIDADE INDUSTRIAL"},
    "A2-156": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-157": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DA FAZENDA PÚBLICA"},
    "A2-158": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS ESPECIAIS DA FAZENDA PÚBLICA"},
    "A2-159": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER"},
    "A2-160": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS ESTADUAIS"},
    "A2-161": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS MUNICIPAIS"},
    "A2-162": {"comarca": "Curiúva", "unidade": "JUÍZO ÚNICO"},
    "A2-163": {"comarca": "Dois Vizinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-164": {"comarca": "Engenheiro Beltrão", "unidade": "JUÍZO ÚNICO"},
    "A2-165": {"comarca": "Faxinal", "unidade": "JUÍZO ÚNICO"},
    "A2-166": {"comarca": "Fazenda Rio Grande", "unidade": "VARA CRIMINAL"},
    "A2-167": {"comarca": "Fazenda Rio Grande", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-168": {"comarca": "Fazenda Rio Grande", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-169": {"comarca": "Fazenda Rio Grande", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-170": {"comarca": "Formosa do Oeste", "unidade": "JUÍZO ÚNICO"},
    "A2-171": {"comarca": "Foz do Iguaçu", "unidade": "1ª VARA CRIMINAL"},
    "A2-172": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA CRIMINAL"},
    "A2-173": {"comarca": "Foz do Iguaçu", "unidade": "3ª VARA CRIMINAL"},
    "A2-174": {"comarca": "Foz do Iguaçu", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-175": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-176": {"comarca": "Foz do Iguaçu", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-177": {"comarca": "Foz do Iguaçu", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-178": {"comarca": "Foz do Iguaçu", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-179": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-180": {"comarca": "Foz do Iguaçu", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-181": {"comarca": "Foz do Iguaçu", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-182": {"comarca": "Foz do Iguaçu", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-183": {"comarca": "Francisco Beltrão", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-184": {"comarca": "Francisco Beltrão", "unidade": "VARA CRIMINAL"},
    "A2-185": {"comarca": "Francisco Beltrão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-186": {"comarca": "Francisco Beltrão", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-187": {"comarca": "Francisco Beltrão", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-188": {"comarca": "Goioerê", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-189": {"comarca": "Goioerê", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-190": {"comarca": "Grandes Rios", "unidade": "JUÍZO ÚNICO"},
    "A2-191": {"comarca": "Guaíra", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-192": {"comarca": "Guaíra", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-193": {"comarca": "Guaraniaçu", "unidade": "JUÍZO ÚNICO"},
    "A2-194": {"comarca": "Guarapuava", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-195": {"comarca": "Guarapuava", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-196": {"comarca": "Guarapuava", "unidade": "1ª VARA CRIMINAL"},
    "A2-197": {"comarca": "Guarapuava", "unidade": "2ª VARA CRIMINAL"},
    "A2-198": {"comarca": "Guarapuava", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-199": {"comarca": "Guarapuava", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-200": {"comarca": "Guarapuava", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-201": {"comarca": "Guarapuava", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-202": {"comarca": "Guarapuava", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-203": {"comarca": "Guarapuava", "unidade": "3ª VARA CRIMINAL"},
    "A2-204": {"comarca": "Guaratuba", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-205": {"comarca": "Ibaiti", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-206": {"comarca": "Ibiporã", "unidade": "VARA CRIMINAL"},
    "A2-207": {"comarca": "Ibiporã", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-208": {"comarca": "Ibiporã", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-209": {"comarca": "Icaraíma", "unidade": "JUÍZO ÚNICO"},
    "A2-210": {"comarca": "Imbituva", "unidade": "JUÍZO ÚNICO"},
    "A2-211": {"comarca": "Ipiranga", "unidade": "JUÍZO ÚNICO"},
    "A2-212": {"comarca": "Iporã", "unidade": "JUÍZO ÚNICO"},
    "A2-213": {"comarca": "Irati", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"},
    "A2-214": {"comarca": "Irati", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-215": {"comarca": "Irati", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS"},
    "A2-216": {"comarca": "Iretama", "unidade": "JUÍZO ÚNICO"},
    "A2-217": {"comarca": "Ivaiporã", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-218": {"comarca": "Ivaiporã", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-219": {"comarca": "Jacarezinho", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-220": {"comarca": "Jacarezinho", "unidade": "VARA CRIMINAL"},
    "A2-221": {"comarca": "Jacarezinho", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-222": {"comarca": "Jacarezinho", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-223": {"comarca": "Jaguapitã", "unidade": "JUÍZO ÚNICO"},
    "A2-224": {"comarca": "Jaguariaíva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-225": {"comarca": "Jandaia do Sul", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-226": {"comarca": "Jandaia do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-227": {"comarca": "Joaquim Távora", "unidade": "JUÍZO ÚNICO"},
    "A2-228": {"comarca": "Lapa", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-229": {"comarca": "Lapa", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-230": {"comarca": "Laranjeiras do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-231": {"comarca": "Loanda", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-232": {"comarca": "Londrina", "unidade": "VARA PRIVATIVA DO TRIBUNAL DO JÚRI"},
    "A2-233": {"comarca": "Londrina", "unidade": "2ª VARA CRIMINAL"},
    "A2-234": {"comarca": "Londrina", "unidade": "3ª VARA CRIMINAL"},
    "A2-235": {"comarca": "Londrina", "unidade": "4ª VARA CRIMINAL"},
    "A2-236": {"comarca": "Londrina", "unidade": "5ª VARA CRIMINAL"},
    "A2-237": {"comarca": "Londrina", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-238": {"comarca": "Londrina", "unidade": "3ª VARA DE FAMÍLIA"},
    "A2-239": {"comarca": "Londrina", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-240": {"comarca": "Londrina", "unidade": "VARA DE SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-241": {"comarca": "Londrina", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-242": {"comarca": "Londrina", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-243": {"comarca": "Londrina", "unidade": "1º JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-244": {"comarca": "Londrina", "unidade": "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-245": {"comarca": "Londrina", "unidade": "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-246": {"comarca": "Londrina", "unidade": "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-247": {"comarca": "Londrina", "unidade": "5º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-248": {"comarca": "Londrina", "unidade": "6º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-249": {"comarca": "Londrina", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-250": {"comarca": "Londrina", "unidade": "11ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-251": {"comarca": "Londrina", "unidade": "1ª VARA DE EXECUÇÕES FISCAIS"},
    "A2-252": {"comarca": "Londrina", "unidade": "2ª VARA DE EXECUÇÕES FISCAIS"},
    "A2-253": {"comarca": "Mallet", "unidade": "JUÍZO ÚNICO"},
    "A2-254": {"comarca": "Mamborê", "unidade": "JUÍZO ÚNICO"},
    "A2-255": {"comarca": "Mandaguaçu", "unidade": "JUÍZO ÚNICO"},
    "A2-256": {"comarca": "Mandaguari", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-257": {"comarca": "Mangueirinha", "unidade": "JUÍZO ÚNICO"},
    "A2-258": {"comarca": "Manoel Ribas", "unidade": "JUÍZO ÚNICO"},
    "A2-259": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA CRIMINAL"},
    "A2-260": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-261": {"comarca": "Marechal Cândido Rondon", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-262": {"comarca": "Marialva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-263": {"comarca": "Marilândia do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-264": {"comarca": "Maringá", "unidade": "3ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-265": {"comarca": "Maringá", "unidade": "4ª VARA CÍVEL"},
    "A2-266": {"comarca": "Maringá", "unidade": "7ª VARA CÍVEL"},
    "A2-267": {"comarca": "Maringá", "unidade": "1ª VARA CRIMINAL"},
    "A2-268": {"comarca": "Maringá", "unidade": "2ª VARA CRIMINAL"},
    "A2-269": {"comarca": "Maringá", "unidade": "3ª VARA CRIMINAL"},
    "A2-270": {"comarca": "Maringá", "unidade": "4ª VARA CRIMINAL"},
    "A2-271": {"comarca": "Maringá", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-272": {"comarca": "Maringá", "unidade": "1ª VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-273": {"comarca": "Maringá", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-274": {"comarca": "Maringá", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-275": {"comarca": "Maringá", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-276": {"comarca": "Maringá", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-277": {"comarca": "Maringá", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-278": {"comarca": "Maringá", "unidade": "5º JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-279": {"comarca": "Maringá", "unidade": "1º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-280": {"comarca": "Maringá", "unidade": "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-281": {"comarca": "Maringá", "unidade": "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-282": {"comarca": "Maringá", "unidade": "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-283": {"comarca": "Marmeleiro", "unidade": "JUÍZO ÚNICO"},
    "A2-284": {"comarca": "Matelândia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-285": {"comarca": "Matinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-286": {"comarca": "Medianeira", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-287": {"comarca": "Morretes", "unidade": "JUÍZO ÚNICO"},
    "A2-288": {"comarca": "Nova Aurora", "unidade": "JUÍZO ÚNICO"},
    "A2-289": {"comarca": "Nova Esperança", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-290": {"comarca": "Nova Esperança", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-291": {"comarca": "Nova Esperança", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-292": {"comarca": "Nova Fátima", "unidade": "JUÍZO ÚNICO"},
    "A2-293": {"comarca": "Nova Londrina", "unidade": "JUÍZO ÚNICO"},
    "A2-294": {"comarca": "Ortigueira", "unidade": "JUÍZO ÚNICO"},
    "A2-295": {"comarca": "Paiçandu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-296": {"comarca": "Paiçandu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-297": {"comarca": "Palmas", "unidade": "VARA CRIMINAL E DA INFÂNCIA E JUVENTUDE"},
    "A2-298": {"comarca": "Palmas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-299": {"comarca": "Palmeira", "unidade": "JUÍZO ÚNICO"},
    "A2-300": {"comarca": "Palmital", "unidade": "JUÍZO ÚNICO"},
    "A2-301": {"comarca": "Palotina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-302": {"comarca": "Paraíso do Norte", "unidade": "JUÍZO ÚNICO"},
    "A2-303": {"comarca": "Paranacity", "unidade": "JUÍZO ÚNICO"},
    "A2-304": {"comarca": "Paranaguá", "unidade": "1ª VARA CÍVEL"},
    "A2-305": {"comarca": "Paranaguá", "unidade": "2ª VARA CÍVEL"},
    "A2-306": {"comarca": "Paranaguá", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-307": {"comarca": "Paranaguá", "unidade": "1ª VARA CRIMINAL"},
    "A2-308": {"comarca": "Paranaguá", "unidade": "2ª VARA CRIMINAL"},
    "A2-309": {"comarca": "Paranaguá", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-310": {"comarca": "Paranaguá", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-311": {"comarca": "Paranaguá", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-312": {"comarca": "Paranavaí", "unidade": "1ª VARA CRIMINAL"},
    "A2-313": {"comarca": "Paranavaí", "unidade": "2ª VARA CRIMINAL"},
    "A2-314": {"comarca": "Paranavaí", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-315": {"comarca": "Paranavaí", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-316": {"comarca": "Pato Branco", "unidade": "VARA CRIMINAL"},
    "A2-317": {"comarca": "Pato Branco", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-318": {"comarca": "Pato Branco", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-319": {"comarca": "Peabiru", "unidade": "JUÍZO ÚNICO"},
    "A2-320": {"comarca": "Pérola", "unidade": "JUÍZO ÚNICO"},
    "A2-321": {"comarca": "Pinhais", "unidade": "VARA CRIMINAL"},
    "A2-322": {"comarca": "Pinhais", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-323": {"comarca": "Pinhais", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-324": {"comarca": "Pinhão", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-325": {"comarca": "Pinhão", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-326": {"comarca": "Piraí do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-327": {"comarca": "Piraquara", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-328": {"comarca": "Piraquara", "unidade": "VARA CRIMINAL"},
    "A2-329": {"comarca": "Piraquara", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-330": {"comarca": "Piraquara", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-331": {"comarca": "Pitanga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-332": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-333": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CRIMINAL"},
    "A2-334": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-335": {"comarca": "Ponta Grossa", "unidade": "3ª VARA CRIMINAL"},
    "A2-336": {"comarca": "Ponta Grossa", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-337": {"comarca": "Ponta Grossa", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-338": {"comarca": "Ponta Grossa", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-339": {"comarca": "Ponta Grossa", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-340": {"comarca": "Ponta Grossa", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-341": {"comarca": "Ponta Grossa", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-342": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-343": {"comarca": "Ponta Grossa", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-344": {"comarca": "Pontal do Paraná", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-345": {"comarca": "Pontal do Paraná", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL CRIMINAL"},
    "A2-346": {"comarca": "Porecatu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-347": {"comarca": "Porecatu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-348": {"comarca": "Primeiro de Maio", "unidade": "JUÍZO ÚNICO"},
    "A2-349": {"comarca": "Prudentópolis", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-350": {"comarca": "Prudentópolis", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-351": {"comarca": "Quatro Barras", "unidade": "JUÍZO ÚNICO"},
    "A2-352": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-353": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-354": {"comarca": "Realeza", "unidade": "JUÍZO ÚNICO"},
    "A2-355": {"comarca": "Rebouças", "unidade": "JUÍZO ÚNICO"},
    "A2-356": {"comarca": "Reserva", "unidade": "JUÍZO ÚNICO"},
    "A2-357": {"comarca": "Ribeirão Claro", "unidade": "JUÍZO ÚNICO"},
    "A2-358": {"comarca": "Ribeirão do Pinhal", "unidade": "JUÍZO ÚNICO"},
    "A2-359": {"comarca": "Rio Branco do Sul", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"},
    "A2-360": {"comarca": "Rio Branco do Sul", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E FAMÍLIA E SUCESSÕES"},
    "A2-361": {"comarca": "Rio Negro", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-362": {"comarca": "Rolândia", "unidade": "VARA CRIMINAL E JUIZADO ESPECIAL CRIMINAL"},
    "A2-363": {"comarca": "Rolândia", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-364": {"comarca": "Rolândia", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-365": {"comarca": "Salto do Lontra", "unidade": "JUÍZO ÚNICO"},
    "A2-366": {"comarca": "Santa Fé", "unidade": "JUÍZO ÚNICO"},
    "A2-367": {"comarca": "Santa Helena", "unidade": "JUÍZO ÚNICO"},
    "A2-368": {"comarca": "Santa Isabel do Ivaí", "unidade": "JUÍZO ÚNICO"},
    "A2-369": {"comarca": "Santa Mariana", "unidade": "JUÍZO ÚNICO"},
    "A2-370": {"comarca": "Santo Antônio da Platina", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-371": {"comarca": "Santo Antônio da Platina", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-372": {"comarca": "Santo Antônio do Sudoeste", "unidade": "JUÍZO ÚNICO"},
    "A2-373": {"comarca": "São Jerônimo da Serra", "unidade": "JUÍZO ÚNICO"},
    "A2-374": {"comarca": "São João", "unidade": "JUÍZO ÚNICO"},
    "A2-375": {"comarca": "São João do Ivaí", "unidade": "JUÍZO ÚNICO"},
    "A2-376": {"comarca": "São João do Triunfo", "unidade": "JUÍZO ÚNICO"},
    "A2-377": {"comarca": "São José dos Pinhais", "unidade": "3ª VARA CÍVEL"},
    "A2-378": {"comarca": "São José dos Pinhais", "unidade": "1ª VARA CRIMINAL"},
    "A2-379": {"comarca": "São José dos Pinhais", "unidade": "2ª VARA CRIMINAL"},
    "A2-380": {"comarca": "São José dos Pinhais", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-381": {"comarca": "São José dos Pinhais", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-382": {"comarca": "São José dos Pinhais", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-383": {"comarca": "São José dos Pinhais", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-384": {"comarca": "São José dos Pinhais", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-385": {"comarca": "São José dos Pinhais", "unidade": "VARA DESCENTRALIZADA DO AFONSO PENA"},
    "A2-386": {"comarca": "São José dos Pinhais", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-387": {"comarca": "São Mateus do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-388": {"comarca": "São Miguel do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-389": {"comarca": "Sarandi", "unidade": "1ª VARA CRIMINAL"},
    "A2-390": {"comarca": "Sarandi", "unidade": "2ª VARA CRIMINAL"},
    "A2-391": {"comarca": "Sarandi", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-392": {"comarca": "Sarandi", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-393": {"comarca": "Sengés", "unidade": "JUÍZO ÚNICO"},
    "A2-394": {"comarca": "Sertanópolis", "unidade": "JUÍZO ÚNICO"},
    "A2-395": {"comarca": "Siqueira Campos", "unidade": "JUÍZO ÚNICO"},
    "A2-396": {"comarca": "Teixeira Soares", "unidade": "JUÍZO ÚNICO"},
    "A2-397": {"comarca": "Telêmaco Borba", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-398": {"comarca": "Telêmaco Borba", "unidade": "VARA CRIMINAL"},
    "A2-399": {"comarca": "Telêmaco Borba", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-400": {"comarca": "Telêmaco Borba", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-401": {"comarca": "Terra Boa", "unidade": "JUÍZO ÚNICO"},
    "A2-402": {"comarca": "Terra Rica", "unidade": "JUÍZO ÚNICO"},
    "A2-403": {"comarca": "Terra Roxa", "unidade": "JUÍZO ÚNICO"},
    "A2-404": {"comarca": "Tibagi", "unidade": "JUÍZO ÚNICO"},
    "A2-405": {"comarca": "Toledo", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-406": {"comarca": "Toledo", "unidade": "1ª VARA CRIMINAL"},
    "A2-407": {"comarca": "Toledo", "unidade": "2ª VARA CRIMINAL"},
    "A2-408": {"comarca": "Toledo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-409": {"comarca": "Toledo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-410": {"comarca": "Toledo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-411": {"comarca": "Tomazina", "unidade": "JUÍZO ÚNICO"},
    "A2-412": {"comarca": "Ubiratã", "unidade": "JUÍZO ÚNICO"},
    "A2-413": {"comarca": "Umuarama", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-414": {"comarca": "Umuarama", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-415": {"comarca": "Umuarama", "unidade": "1ª VARA CRIMINAL"},
    "A2-416": {"comarca": "Umuarama", "unidade": "2ª VARA CRIMINAL"},
    "A2-417": {"comarca": "Umuarama", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-418": {"comarca": "Umuarama", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-419": {"comarca": "União da Vitória", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-420": {"comarca": "União da Vitória", "unidade": "1ª VARA CRIMINAL"},
    "A2-421": {"comarca": "União da Vitória", "unidade": "2ª VARA CRIMINAL"},
    "A2-422": {"comarca": "União da Vitória", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-423": {"comarca": "União da Vitória", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-424": {"comarca": "Uraí", "unidade": "JUÍZO ÚNICO"},
    "A2-425": {"comarca": "Wenceslau Braz", "unidade": "JUÍZO ÚNICO"},
    "A2-426": {"comarca": "Xambrê", "unidade": "JUÍZO ÚNICO"},
    "A2-427": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-428": {"comarca": "Alto Paraná", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-429": {"comarca": "Alto Piquiri", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-430": {"comarca": "Altônia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-431": {"comarca": "Ampére", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-432": {"comarca": "Andirá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-433": {"comarca": "Antonina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-434": {"comarca": "Apucarana", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 10},
    "A2-435": {"comarca": "Arapongas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 10},
    "A2-436": {"comarca": "Arapoti", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-437": {"comarca": "Araucária", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 9},
    "A2-438": {"comarca": "Assaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-439": {"comarca": "Assis Chateaubriand", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-440": {"comarca": "Astorga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-441": {"comarca": "Bandeirantes", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-442": {"comarca": "Barbosa Ferraz", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-443": {"comarca": "Barracão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-444": {"comarca": "Bela Vista Do Paraíso", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-445": {"comarca": "Bocaiúva Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-446": {"comarca": "Cambará", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-447": {"comarca": "Cambé", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-448": {"comarca": "Campina Da Lagoa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-449": {"comarca": "Campina Grande Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-450": {"comarca": "Campo Largo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-451": {"comarca": "Campo Mourão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-452": {"comarca": "Cândido De Abreu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-453": {"comarca": "Cantagalo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-454": {"comarca": "Capanema", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-455": {"comarca": "Capitão Leônidas Marques", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-456": {"comarca": "Carlópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-457": {"comarca": "Cascavel", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 28},
    "A2-458": {"comarca": "Castro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-459": {"comarca": "Catanduvas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-460": {"comarca": "Centenário Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-461": {"comarca": "Cerro Azul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-462": {"comarca": "Chopinzinho", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-463": {"comarca": "Cianorte", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-464": {"comarca": "Cidade Gaúcha", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-465": {"comarca": "Clevelândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-466": {"comarca": "Colombo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 13},
    "A2-467": {"comarca": "Colorado", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-468": {"comarca": "Congonhinhas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-469": {"comarca": "Corbélia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-470": {"comarca": "Cornélio Procópio", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-471": {"comarca": "Coronel Vivida", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-472": {"comarca": "Cruzeiro Do Oeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-473": {"comarca": "Curitiba", "unidade": "SECRETARIAS DAS DIREÇÕES DOS FÓRUNS", "quantidade": 39},
    "A2-474": {"comarca": "Curiúva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-475": {"comarca": "Dois Vizinhos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-476": {"comarca": "Engenheiro Beltrão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-477": {"comarca": "Faxinal", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-478": {"comarca": "Fazenda Rio Grande", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 10},
    "A2-479": {"comarca": "Formosa Do Oeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-480": {"comarca": "Foz Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 23},
    "A2-481": {"comarca": "Francisco Beltrão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 13},
    "A2-482": {"comarca": "Goioerê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-483": {"comarca": "Grandes Rios", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-484": {"comarca": "Guaíra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-485": {"comarca": "Guaraniaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-486": {"comarca": "Guarapuava", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 23},
    "A2-487": {"comarca": "Guaratuba", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-488": {"comarca": "Ibaiti", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-489": {"comarca": "Ibiporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-490": {"comarca": "Icaraíma", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-491": {"comarca": "Imbituva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-492": {"comarca": "Ipiranga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-493": {"comarca": "Iporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-494": {"comarca": "Irati", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-495": {"comarca": "Iretama", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-496": {"comarca": "Ivaiporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-497": {"comarca": "Jacarezinho", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-498": {"comarca": "Jaguapitã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-499": {"comarca": "Jaguariaíva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-500": {"comarca": "Jandaia Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-501": {"comarca": "Joaquim Távora", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-502": {"comarca": "Lapa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-503": {"comarca": "Laranjeiras Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 7},
    "A2-504": {"comarca": "Loanda", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-505": {"comarca": "Londrina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 51},
    "A2-506": {"comarca": "Mallet", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-507": {"comarca": "Mamborê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-508": {"comarca": "Mandaguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-509": {"comarca": "Mandaguari", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-510": {"comarca": "Mangueirinha", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-511": {"comarca": "Manoel Ribas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-512": {"comarca": "Marechal Cândido Rondon", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-513": {"comarca": "Marialva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-514": {"comarca": "Marilândia Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-515": {"comarca": "Maringá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 28},
    "A2-516": {"comarca": "Marmeleiro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-517": {"comarca": "Matelândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-518": {"comarca": "Matinhos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-519": {"comarca": "Medianeira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-520": {"comarca": "Morretes", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-521": {"comarca": "Nova Aurora", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-522": {"comarca": "Nova Esperança", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-523": {"comarca": "Nova Fátima", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-524": {"comarca": "Nova Londrina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 2},
    "A2-525": {"comarca": "Ortigueira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-526": {"comarca": "Paiçandu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-527": {"comarca": "Palmas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 7},
    "A2-528": {"comarca": "Palmeira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-529": {"comarca": "Palmital", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-530": {"comarca": "Palotina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-531": {"comarca": "Paraíso Do Norte", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-532": {"comarca": "Paranacity", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-533": {"comarca": "Paranaguá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 12},
    "A2-534": {"comarca": "Paranavaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 10},
    "A2-535": {"comarca": "Pato Branco", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 9},
    "A2-536": {"comarca": "Peabiru", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-537": {"comarca": "Pérola", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-538": {"comarca": "Pinhais", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-539": {"comarca": "Pinhão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-540": {"comarca": "Piraí Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-541": {"comarca": "Piraquara", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-542": {"comarca": "Pitanga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-543": {"comarca": "Ponta Grossa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 28},
    "A2-544": {"comarca": "Pontal Do Paraná", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-545": {"comarca": "Porecatu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-546": {"comarca": "Primeiro De Maio", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-547": {"comarca": "Prudentópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-548": {"comarca": "Quatro Barras", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-549": {"comarca": "Quedas Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-550": {"comarca": "Realeza", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-551": {"comarca": "Rebouças", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-552": {"comarca": "Reserva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-553": {"comarca": "Ribeirão Claro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-554": {"comarca": "Ribeirão Do Pinhal", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-555": {"comarca": "Rio Branco Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-556": {"comarca": "Rio Negro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-557": {"comarca": "Rolândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-558": {"comarca": "Salto Do Lontra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-559": {"comarca": "Santa Fé", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-560": {"comarca": "Santa Helena", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-561": {"comarca": "Santa Isabel Do Ivaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-562": {"comarca": "Santa Mariana", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-563": {"comarca": "Santo Antônio Da Platina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 5},
    "A2-564": {"comarca": "Santo Antônio Do Sudoeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-565": {"comarca": "São Jerônimo Da Serra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-566": {"comarca": "São João", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-567": {"comarca": "São João Do Ivaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-568": {"comarca": "São João Do Triunfo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-569": {"comarca": "São José Dos Pinhais", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 20},
    "A2-570": {"comarca": "São Mateus Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-571": {"comarca": "São Miguel Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-572": {"comarca": "Sarandi", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 8},
    "A2-573": {"comarca": "Sengés", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-574": {"comarca": "Sertanópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-575": {"comarca": "Siqueira Campos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-576": {"comarca": "Teixeira Soares", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-577": {"comarca": "Telêmaco Borba", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 6},
    "A2-578": {"comarca": "Terra Boa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 4},
    "A2-579": {"comarca": "Terra Rica", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-580": {"comarca": "Terra Roxa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-581": {"comarca": "Tibagi", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-582": {"comarca": "Toledo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 10},
    "A2-583": {"comarca": "Tomazina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-584": {"comarca": "Ubiratã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-585": {"comarca": "Umuarama", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 15},
    "A2-586": {"comarca": "União Da Vitória", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 14},
    "A2-587": {"comarca": "Uraí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-588": {"comarca": "Wenceslau Braz", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-589": {"comarca": "Xambrê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM", "quantidade": 3},
    "A2-590": {"comarca": "Cambé", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
}

# Total de vagas do Anexo I
TOTAL_VAGAS_ANEXO_I = sum(v["quantidade"] for v in ANEXO_I.values())
