
# =============================================================================
# ANEXO II - Todas as unidades judiciarias
# Formato: "CODIGO": {"comarca": "...", "unidade": "..."}
# =============================================================================

ANEXO_II = {
    "A2-001": {"comarca": "Almirante Tamandaré", "unidade": "1ª VARA CRIMINAL"},
    "A2-002": {"comarca": "Almirante Tamandaré", "unidade": "2ª VARA CRIMINAL"},
    "A2-003": {"comarca": "Almirante Tamandaré", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-004": {"comarca": "Almirante Tamandaré", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-005": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS E DA FAZENDA PÚBLICA"},
    "A2-006": {"comarca": "Alto Paraná", "unidade": "JUÍZO ÚNICO"},
    "A2-007": {"comarca": "Alto Piquiri", "unidade": "JUÍZO ÚNICO"},
    "A2-008": {"comarca": "Altônia", "unidade": "JUÍZO ÚNICO"},
    "A2-009": {"comarca": "Ampére", "unidade": "JUÍZO ÚNICO"},
    "A2-010": {"comarca": "Andirá", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-011": {"comarca": "Antonina", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-012": {"comarca": "Antonina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-013": {"comarca": "Apucarana", "unidade": "1ª VARA CRIMINAL"},
    "A2-014": {"comarca": "Apucarana", "unidade": "2ª VARA CRIMINAL"},
    "A2-015": {"comarca": "Apucarana", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-016": {"comarca": "Apucarana", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-017": {"comarca": "Arapongas", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-018": {"comarca": "Arapongas", "unidade": "1ª VARA CRIMINAL"},
    "A2-019": {"comarca": "Arapongas", "unidade": "2ª VARA CRIMINAL"},
    "A2-020": {"comarca": "Arapongas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-021": {"comarca": "Arapongas", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-022": {"comarca": "Arapoti", "unidade": "JUÍZO ÚNICO"},
    "A2-023": {"comarca": "Araucária", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-024": {"comarca": "Araucária", "unidade": "VARA CRIMINAL"},
    "A2-025": {"comarca": "Araucária", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-026": {"comarca": "Araucária", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-027": {"comarca": "Assaí", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-028": {"comarca": "Assis Chatea ubria nd", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-029": {"comarca": "Astorga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-030": {"comarca": "Bandeirantes", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-031": {"comarca": "Bandeirantes", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-032": {"comarca": "Barbosa Ferraz", "unidade": "JUÍZO ÚNICO"},
    "A2-033": {"comarca": "Barracão", "unidade": "JUÍZO ÚNICO"},
    "A2-034": {"comarca": "Bela Vista do Paraíso", "unidade": "JUÍZO ÚNICO"},
    "A2-035": {"comarca": "Bocaiúva do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-036": {"comarca": "Cambará", "unidade": "JUÍZO ÚNICO"},
    "A2-037": {"comarca": "Cambé", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-038": {"comarca": "Cambé", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-039": {"comarca": "Cambé", "unidade": "VARA CRIMINAL"},
    "A2-040": {"comarca": "Cambé", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-041": {"comarca": "Cambé", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-042": {"comarca": "Campina da Lagoa", "unidade": "JUÍZO ÚNICO"},
    "A2-043": {"comarca": "Campina Grande do Sul", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-044": {"comarca": "Campina Grande do Sul", "unidade": "VARA CRIMINAL"},
    "A2-045": {"comarca": "Campina Grande do Sul", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA E DA INFÂNCIA E JUVENTUDE"},
    "A2-046": {"comarca": "Campo Largo", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-047": {"comarca": "Campo Largo", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-048": {"comarca": "Campo Largo", "unidade": "VARA CRIMINAL"},
    "A2-049": {"comarca": "Campo Largo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-050": {"comarca": "Campo Largo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-051": {"comarca": "Campo Mourão", "unidade": "1ª VARA CRIMINAL"},
    "A2-052": {"comarca": "Campo Mourão", "unidade": "2ª VARA CRIMINAL"},
    "A2-053": {"comarca": "Campo Mourão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-054": {"comarca": "Campo Mourão", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-055": {"comarca": "Cândido de Abreu", "unidade": "JUÍZO ÚNICO"},
    "A2-056": {"comarca": "Cantagalo", "unidade": "JUÍZO ÚNICO"},
    "A2-057": {"comarca": "Capanema", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-058": {"comarca": "Capitão Leônidas Marques", "unidade": "JUÍZO ÚNICO"},
    "A2-059": {"comarca": "Carlópolis", "unidade": "JUÍZO ÚNICO"},
    "A2-060": {"comarca": "Cascavel", "unidade": "4ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-061": {"comarca": "Cascavel", "unidade": "Sª VARA CÍVEL"},
    "A2-062": {"comarca": "Cascavel", "unidade": "1ª VARA CRIMINAL"},
    "A2-063": {"comarca": "Cascavel", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-064": {"comarca": "Cascavel", "unidade": "3ª VARA CRIMINAL"},
    "A2-065": {"comarca": "Cascavel", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-066": {"comarca": "Cascavel", "unidade": "1ª VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-067": {"comarca": "Cascavel", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-068": {"comarca": "Cascavel", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-069": {"comarca": "Cascavel", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-070": {"comarca": "Cascavel", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-071": {"comarca": "Cascavel", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-072": {"comarca": "Cascavel", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-073": {"comarca": "Cascavel", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-074": {"comarca": "Cascavel", "unidade": "4ª VARA CRIMINAL"},
    "A2-075": {"comarca": "Castro", "unidade": "VARA CRIMINAL"},
    "A2-076": {"comarca": "Castro", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-077": {"comarca": "Castro", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-078": {"comarca": "Catanduvas", "unidade": "JUÍZO ÚNICO"},
    "A2-079": {"comarca": "Centenário do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-080": {"comarca": "Cerro Azul", "unidade": "JUÍZO ÚNICO"},
    "A2-081": {"comarca": "Chopinzinho", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-082": {"comarca": "Cianorte", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-083": {"comarca": "Cianorte", "unidade": "VARA CRIMINAL"},
    "A2-084": {"comarca": "Cianorte", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-085": {"comarca": "Cianorte", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-086": {"comarca": "Cidade Gaúcha", "unidade": "JUÍZO ÚNICO"},
    "A2-087": {"comarca": "Clevelândia", "unidade": "JUÍZO ÚNICO"},
    "A2-088": {"comarca": "Colombo", "unidade": "2ª VARA CÍVEL"},
    "A2-089": {"comarca": "Colombo", "unidade": "1ª VARA CRIMINAL"},
    "A2-090": {"comarca": "Colombo", "unidade": "2ª VARA CRIMINAL"},
    "A2-091": {"comarca": "Colombo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-092": {"comarca": "Colombo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-093": {"comarca": "Colombo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-094": {"comarca": "Colombo", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-095": {"comarca": "Colorado", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-096": {"comarca": "Congonhinhas", "unidade": "JUÍZO ÚNICO"},
    "A2-097": {"comarca": "Corbélia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-098": {"comarca": "Cornélia Procópio", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-099": {"comarca": "Cornélia Procópio", "unidade": "VARA CRIMINAL"},
    "A2-100": {"comarca": "Cornélia Procópio", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-101": {"comarca": "Cornélia Procópio", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-102": {"comarca": "Coronel Vivida", "unidade": "JUÍZO ÚNICO"},
    "A2-103": {"comarca": "Cruzeiro do Oeste", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-104": {"comarca": "Cruzeiro do Oeste", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-105": {"comarca": "Curitiba", "unidade": "3ª VARA CÍVEL"},
    "A2-106": {"comarca": "Curitiba", "unidade": "10ª VARA CÍVEL"},
    "A2-107": {"comarca": "Curitiba", "unidade": "12ª VARA CÍVEL"},
    "A2-108": {"comarca": "Curitiba", "unidade": "15ª VARA CÍVEL"},
    "A2-109": {"comarca": "Curitiba", "unidade": "18ª VARA CÍVEL"},
    "A2-110": {"comarca": "Curitiba", "unidade": "23ª VARA CÍVEL"},
    "A2-111": {"comarca": "Curitiba", "unidade": "24ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-112": {"comarca": "Curitiba", "unidade": "25ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-113": {"comarca": "Curitiba", "unidade": "26ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-114": {"comarca": "Curitiba", "unidade": "27ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-115": {"comarca": "Curitiba", "unidade": "1ª VARA DE FAMÍLIA"},
    "A2-116": {"comarca": "Curitiba", "unidade": "3ª VARA DE FAMÍLIA"},
    "A2-117": {"comarca": "Curitiba", "unidade": "5ª VARA DE FAMÍLIA"},
    "A2-118": {"comarca": "Curitiba", "unidade": "6ª VARA DE FAMÍLIA"},
    "A2-119": {"comarca": "Curitiba", "unidade": "14º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-120": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DA CIDADE INDUSTRIAL"},
    "A2-121": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-122": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DA FAZENDA PÚBLICA"},
    "A2-123": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS ESPECIAIS DA FAZENDA PÚBLICA"},
    "A2-124": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER"},
    "A2-125": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS ESTADUAIS"},
    "A2-126": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS MUNICIPAIS"},
    "A2-127": {"comarca": "Curiúva", "unidade": "JUÍZO ÚNICO"},
    "A2-128": {"comarca": "Dois Vizinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-129": {"comarca": "Engenheiro Beltrão", "unidade": "JUÍZO ÚNICO"},
    "A2-130": {"comarca": "Faxinai", "unidade": "JUÍZO ÚNICO"},
    "A2-131": {"comarca": "Fazenda Rio Grande", "unidade": "VARA CRIMINAL"},
    "A2-132": {"comarca": "Fazenda Rio Grande", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-133": {"comarca": "Fazenda Rio Grande", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-134": {"comarca": "Fazenda Rio Grande", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-135": {"comarca": "Formosa do Oeste", "unidade": "JUÍZO ÚNICO"},
    "A2-136": {"comarca": "Foz do Iguaçu", "unidade": "1ª VARA CRIMINAL"},
    "A2-137": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA CRIMINAL"},
    "A2-138": {"comarca": "Foz do Iguaçu", "unidade": "3ª VARA CRIMINAL"},
    "A2-139": {"comarca": "Foz do Iguaçu", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-140": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-141": {"comarca": "Foz do Iguaçu", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-142": {"comarca": "Foz do Iguaçu", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-143": {"comarca": "Foz do Iguaçu", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-144": {"comarca": "Foz do Iguaçu", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-145": {"comarca": "Foz do Iguaçu", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-146": {"comarca": "Foz do Iguaçu", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-147": {"comarca": "Foz do Iguaçu", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-148": {"comarca": "Francisco Beltrão", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-149": {"comarca": "Francisco Beltrão", "unidade": "VARA CRIMINAL"},
    "A2-150": {"comarca": "Francisco Beltrão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-151": {"comarca": "Francisco Beltrão", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-152": {"comarca": "Francisco Beltrão", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-153": {"comarca": "Goioerê", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-154": {"comarca": "Goioerê", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-155": {"comarca": "Grandes Rios", "unidade": "JUÍZO ÚNICO"},
    "A2-156": {"comarca": "Guaíra", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-157": {"comarca": "Guaíra", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-158": {"comarca": "Guaraniaçu", "unidade": "JUÍZO ÚNICO"},
    "A2-159": {"comarca": "Guarapuava", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-160": {"comarca": "Guarapuava", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-161": {"comarca": "Guarapuava", "unidade": "1ª VARA CRIMINAL"},
    "A2-162": {"comarca": "Guarapuava", "unidade": "2ª VARA CRIMINAL"},
    "A2-163": {"comarca": "Guarapuava", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-164": {"comarca": "Guarapuava", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-165": {"comarca": "Guarapuava", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-166": {"comarca": "Guarapuava", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-167": {"comarca": "Guarapuava", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-168": {"comarca": "Guarapuava", "unidade": "3ª VARA CRIMINAL"},
    "A2-169": {"comarca": "Guaratuba", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-170": {"comarca": "1 baiti", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-171": {"comarca": "lbiporã", "unidade": "VARA CRIMINAL"},
    "A2-172": {"comarca": "lbiporã", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-173": {"comarca": "lbiporã", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-174": {"comarca": "lcaraíma", "unidade": "JUÍZO ÚNICO"},
    "A2-175": {"comarca": "lmbituva", "unidade": "JUÍZO ÚNICO"},
    "A2-176": {"comarca": "lpiranga", "unidade": "JUÍZO ÚNICO"},
    "A2-177": {"comarca": "lporã", "unidade": "JUÍZO ÚNICO"},
    "A2-178": {"comarca": "1 rati", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"},
    "A2-179": {"comarca": "1 rati", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-180": {"comarca": "1 rati", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS"},
    "A2-181": {"comarca": "lretama", "unidade": "JUÍZO ÚNICO"},
    "A2-182": {"comarca": "lvaiporã", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-183": {"comarca": "lvaiporã", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-184": {"comarca": "Jacarezinho", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-185": {"comarca": "Jacarezinho", "unidade": "VARA CRIMINAL"},
    "A2-186": {"comarca": "Jacarezinho", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-187": {"comarca": "Jacarezinho", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-188": {"comarca": "Jaguapitã", "unidade": "JUÍZO ÚNICO"},
    "A2-189": {"comarca": "Jaguariaíva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-190": {"comarca": "Jandaia do Sul", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-191": {"comarca": "Jandaia do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-192": {"comarca": "Joaquim Távora", "unidade": "JUÍZO ÚNICO"},
    "A2-193": {"comarca": "Lapa", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-194": {"comarca": "Lapa", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-195": {"comarca": "Laranjeiras do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-196": {"comarca": "Loanda", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-197": {"comarca": "Londrina", "unidade": "VARA PRIVATIVA DO TRIBUNAL DO JÚRI"},
    "A2-198": {"comarca": "Londrina", "unidade": "2ª VARA CRIMINAL"},
    "A2-199": {"comarca": "Londrina", "unidade": "3ª VARA CRIMINAL"},
    "A2-200": {"comarca": "Londrina", "unidade": "4ª VARA CRIMINAL"},
    "A2-201": {"comarca": "Londrina", "unidade": "Sª VARA CRIMINAL"},
    "A2-202": {"comarca": "Londrina", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-203": {"comarca": "Londrina", "unidade": "3ª VARA DE FAMÍLIA"},
    "A2-204": {"comarca": "Londrina", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-205": {"comarca": "Londrina", "unidade": "VARA DE SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-206": {"comarca": "Londrina", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-207": {"comarca": "Londrina", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-208": {"comarca": "Londrina", "unidade": "1º JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-209": {"comarca": "Londrina", "unidade": "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-210": {"comarca": "Londrina", "unidade": "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-211": {"comarca": "Londrina", "unidade": "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-212": {"comarca": "Londrina", "unidade": "Sº JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-213": {"comarca": "Londrina", "unidade": "6º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-214": {"comarca": "Londrina", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-215": {"comarca": "Londrina", "unidade": "11ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-216": {"comarca": "Londrina", "unidade": "1ª VARA DE EXECUÇÕES FISCAIS"},
    "A2-217": {"comarca": "Londrina", "unidade": "2ª VARA DE EXECUÇÕES FISCAIS"},
    "A2-218": {"comarca": "Mallet", "unidade": "JUÍZO ÚNICO"},
    "A2-219": {"comarca": "Mamborê", "unidade": "JUÍZO ÚNICO"},
    "A2-220": {"comarca": "Mandaguaçu", "unidade": "JUÍZO ÚNICO"},
    "A2-221": {"comarca": "Mandaguari", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-222": {"comarca": "Mangueirinha", "unidade": "JUÍZO ÚNICO"},
    "A2-223": {"comarca": "Manoel Ribas", "unidade": "JUÍZO ÚNICO"},
    "A2-224": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA CRIMINAL"},
    "A2-225": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-226": {"comarca": "Marechal Cândido Rondon", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-227": {"comarca": "Marialva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-228": {"comarca": "Marilândia do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-229": {"comarca": "Maringá", "unidade": "3ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-230": {"comarca": "Maringá", "unidade": "4ª VARA CÍVEL"},
    "A2-231": {"comarca": "Maringá", "unidade": "7ª VARA CÍVEL"},
    "A2-232": {"comarca": "Maringá", "unidade": "1ª VARA CRIMINAL"},
    "A2-233": {"comarca": "Maringá", "unidade": "2ª VARA CRIMINAL"},
    "A2-234": {"comarca": "Maringá", "unidade": "3ª VARA CRIMINAL"},
    "A2-235": {"comarca": "Maringá", "unidade": "4ª VARA CRIMINAL"},
    "A2-236": {"comarca": "Maringá", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-237": {"comarca": "Maringá", "unidade": "1ª VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-238": {"comarca": "Maringá", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"},
    "A2-239": {"comarca": "Maringá", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-240": {"comarca": "Maringá", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-241": {"comarca": "Maringá", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-242": {"comarca": "Maringá", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-243": {"comarca": "Maringá", "unidade": "Sº JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-244": {"comarca": "Maringá", "unidade": "1º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-245": {"comarca": "Maringá", "unidade": "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-246": {"comarca": "Maringá", "unidade": "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-247": {"comarca": "Maringá", "unidade": "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"},
    "A2-248": {"comarca": "Marmeleiro", "unidade": "JUÍZO ÚNICO"},
    "A2-249": {"comarca": "Matelândia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-250": {"comarca": "Matinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-251": {"comarca": "Medianeira", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-252": {"comarca": "Marretes", "unidade": "JUÍZO ÚNICO"},
    "A2-253": {"comarca": "Nova Aurora", "unidade": "JUÍZO ÚNICO"},
    "A2-254": {"comarca": "Nova Esperança", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-255": {"comarca": "Nova Esperança", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"},
    "A2-256": {"comarca": "Nova Esperança", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-257": {"comarca": "Nova Fátima", "unidade": "JUÍZO ÚNICO"},
    "A2-258": {"comarca": "Nova Londrina", "unidade": "JUÍZO ÚNICO"},
    "A2-259": {"comarca": "Ortigueira", "unidade": "JUÍZO ÚNICO"},
    "A2-260": {"comarca": "Paiçandu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-261": {"comarca": "Paiçandu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-262": {"comarca": "Palmas", "unidade": "VARA CRIMINAL E DA INFÂNCIA E JUVENTUDE"},
    "A2-263": {"comarca": "Palmas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-264": {"comarca": "Palmeira", "unidade": "JUÍZO ÚNICO"},
    "A2-265": {"comarca": "Palmital", "unidade": "JUÍZO ÚNICO"},
    "A2-266": {"comarca": "Palatina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-267": {"comarca": "Paraíso do Norte", "unidade": "JUÍZO ÚNICO"},
    "A2-268": {"comarca": "Paranacity", "unidade": "JUÍZO ÚNICO"},
    "A2-269": {"comarca": "Paranaguá", "unidade": "1ª VARA CÍVEL"},
    "A2-270": {"comarca": "Paranaguá", "unidade": "2ª VARA CÍVEL"},
    "A2-271": {"comarca": "Paranaguá", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-272": {"comarca": "Paranaguá", "unidade": "1ª VARA CRIMINAL"},
    "A2-273": {"comarca": "Paranaguá", "unidade": "2ª VARA CRIMINAL"},
    "A2-274": {"comarca": "Paranaguá", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-275": {"comarca": "Paranaguá", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-276": {"comarca": "Paranaguá", "unidade": "VARA DA FAZENDA PÚBLICA"},
    "A2-277": {"comarca": "Paranavaí", "unidade": "1ª VARA CRIMINAL"},
    "A2-278": {"comarca": "Paranavaí", "unidade": "2ª VARA CRIMINAL"},
    "A2-279": {"comarca": "Paranavaí", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-280": {"comarca": "Paranavaí", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-281": {"comarca": "Pato Branco", "unidade": "VARA CRIMINAL"},
    "A2-282": {"comarca": "Pato Branco", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-283": {"comarca": "Pato Branco", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-284": {"comarca": "Peabiru", "unidade": "JUÍZO ÚNICO"},
    "A2-285": {"comarca": "Pérola", "unidade": "JUÍZO ÚNICO"},
    "A2-286": {"comarca": "Pinhais", "unidade": "VARA CRIMINAL"},
    "A2-287": {"comarca": "Pinhais", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-288": {"comarca": "Pinhais", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-289": {"comarca": "Pinhão", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-290": {"comarca": "Pinhão", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-291": {"comarca": "Piraí do Sul", "unidade": "JUÍZO ÚNICO"},
    "A2-292": {"comarca": "Piraquara", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-293": {"comarca": "Piraquara", "unidade": "VARA CRIMINAL"},
    "A2-294": {"comarca": "Piraquara", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-295": {"comarca": "Piraquara", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-296": {"comarca": "Pitanga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-297": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CÍVEL E EMPRESARIAL REGIONAL"},
    "A2-298": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CRIMINAL"},
    "A2-299": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-300": {"comarca": "Ponta Grossa", "unidade": "3ª VARA CRIMINAL"},
    "A2-301": {"comarca": "Ponta Grossa", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"},
    "A2-302": {"comarca": "Ponta Grossa", "unidade": "VARA DA INFÂNCIA E JUVENTUDE"},
    "A2-303": {"comarca": "Ponta Grossa", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"},
    "A2-304": {"comarca": "Ponta Grossa", "unidade": "1ª VARA DA FAZENDA PÚBLICA"},
    "A2-305": {"comarca": "Ponta Grossa", "unidade": "2ª VARA DA FAZENDA PÚBLICA"},
    "A2-306": {"comarca": "Ponta Grossa", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-307": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-308": {"comarca": "Ponta Grossa", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-309": {"comarca": "Pontal do Paraná", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-310": {"comarca": "Pontal do Paraná", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL CRIMINAL"},
    "A2-311": {"comarca": "Porecatu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-312": {"comarca": "Porecatu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-313": {"comarca": "Primeiro de Maio", "unidade": "JUÍZO ÚNICO"},
    "A2-314": {"comarca": "Prudentópolis", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-315": {"comarca": "Prudentópolis", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-316": {"comarca": "Quatro Barras", "unidade": "JUÍZO ÚNICO"},
    "A2-317": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"},
    "A2-318": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-319": {"comarca": "Realeza", "unidade": "JUÍZO ÚNICO"},
    "A2-320": {"comarca": "Rebouças", "unidade": "JUÍZO ÚNICO"},
    "A2-321": {"comarca": "Reserva", "unidade": "JUÍZO ÚNICO"},
    "A2-322": {"comarca": "Ribeirão Claro", "unidade": "JUÍZO ÚNICO"},
    "A2-323": {"comarca": "Ribeirão do Pinhal", "unidade": "JUÍZO ÚNICO"},
    "A2-324": {"comarca": "Rio Branco do Sul", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"},
    "A2-325": {"comarca": "Rio Branco do Sul", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E FAMÍLIA E SUCESSÕES"},
    "A2-326": {"comarca": "Rio Negro", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"},
    "A2-327": {"comarca": "Rolândia", "unidade": "VARA CRIMINAL E JUIZADO ESPECIAL CRIMINAL"},
    "A2-328": {"comarca": "Rolândia", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-329": {"comarca": "Rolândia", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-330": {"comarca": "Salto do Lontra", "unidade": "JUÍZO ÚNICO"},
    "A2-331": {"comarca": "Santa Fé", "unidade": "JUÍZO ÚNICO"},
    "A2-332": {"comarca": "Sarandi", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-333": {"comarca": "Sengés", "unidade": "JUÍZO ÚNICO"},
    "A2-334": {"comarca": "Sertanópolis", "unidade": "JUÍZO ÚNICO"},
    "A2-335": {"comarca": "Siqueira Campos", "unidade": "JUÍZO ÚNICO"},
    "A2-336": {"comarca": "Teixeira Soares", "unidade": "JUÍZO ÚNICO"},
    "A2-337": {"comarca": "Telêmaco Borba", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-338": {"comarca": "Telêmaco Borba", "unidade": "VARA CRIMINAL"},
    "A2-339": {"comarca": "Telêmaco Borba", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-340": {"comarca": "Telêmaco Borba", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-341": {"comarca": "Terra Boa", "unidade": "JUÍZO ÚNICO"},
    "A2-342": {"comarca": "Terra Rica", "unidade": "JUÍZO ÚNICO"},
    "A2-343": {"comarca": "Terra Roxa", "unidade": "JUÍZO ÚNICO"},
    "A2-344": {"comarca": "Tibagi", "unidade": "JUÍZO ÚNICO"},
    "A2-345": {"comarca": "Toledo", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-346": {"comarca": "Toledo", "unidade": "1ª VARA CRIMINAL"},
    "A2-347": {"comarca": "Toledo", "unidade": "2ª VARA CRIMINAL"},
    "A2-348": {"comarca": "Toledo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-349": {"comarca": "Toledo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES"},
    "A2-350": {"comarca": "Toledo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-351": {"comarca": "Tomazina", "unidade": "JUÍZO ÚNICO"},
    "A2-352": {"comarca": "Ubiratã", "unidade": "JUÍZO ÚNICO"},
    "A2-353": {"comarca": "Umuarama", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-354": {"comarca": "Umuarama", "unidade": "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-355": {"comarca": "Umuarama", "unidade": "1ª VARA CRIMINAL"},
    "A2-356": {"comarca": "Umuarama", "unidade": "2ª VARA CRIMINAL"},
    "A2-357": {"comarca": "Umuarama", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-358": {"comarca": "Umuarama", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-359": {"comarca": "União da Vitória", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"},
    "A2-360": {"comarca": "União da Vitória", "unidade": "1ª VARA CRIMINAL"},
    "A2-361": {"comarca": "União da Vitória", "unidade": "2ª VARA CRIMINAL"},
    "A2-362": {"comarca": "União da Vitória", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"},
    "A2-363": {"comarca": "União da Vitória", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"},
    "A2-364": {"comarca": "Uraí", "unidade": "JUÍZO ÚNICO"},
    "A2-365": {"comarca": "Wenceslau Braz", "unidade": "JUÍZO ÚNICO"},
    "A2-366": {"comarca": "Xambrê", "unidade": "JUÍZO ÚNICO"},
    "A2-367": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-368": {"comarca": "Alto Paraná", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-369": {"comarca": "Alto Piquiri", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-370": {"comarca": "Altônia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-371": {"comarca": "Ampére", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-372": {"comarca": "Andirá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-373": {"comarca": "Antonina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-374": {"comarca": "Apucarana", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-375": {"comarca": "Arapongas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-376": {"comarca": "Arapoti", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-377": {"comarca": "Araucária", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-378": {"comarca": "Assaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-379": {"comarca": "Assis Chateaubriand", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-380": {"comarca": "Astorga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-381": {"comarca": "Bandeirantes", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-382": {"comarca": "Barbosa Ferraz", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-383": {"comarca": "Barracão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-384": {"comarca": "Bela Vista Do Paraíso", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-385": {"comarca": "Bocaiúva Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-386": {"comarca": "Cambará", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-387": {"comarca": "Cambé", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-388": {"comarca": "Campina Da Lagoa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-389": {"comarca": "Campina Grande Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-390": {"comarca": "Campo Largo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-391": {"comarca": "Campo Mourão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-392": {"comarca": "Cândido De Abreu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-393": {"comarca": "Canta galo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-394": {"comarca": "Capanema", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-395": {"comarca": "Capitão Leônidas Marques", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-396": {"comarca": "Carlópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-397": {"comarca": "Cascavel", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-398": {"comarca": "Castro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-399": {"comarca": "Catanduvas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-400": {"comarca": "Centenário Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-401": {"comarca": "Cerro Azul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-402": {"comarca": "Chopinzinho", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-403": {"comarca": "Cianorte", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-404": {"comarca": "Cidade Gaúcha", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-405": {"comarca": "Clevelândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-406": {"comarca": "Colombo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-407": {"comarca": "Colorado", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-408": {"comarca": "Congonhinhas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-409": {"comarca": "Corbélia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-410": {"comarca": "Cornélia Procópio", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-411": {"comarca": "Coronel Vivida", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-412": {"comarca": "Cruzeiro Do Oeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-413": {"comarca": "Curitiba", "unidade": "SECRETARIAS DAS DIREÇÕES DOS FÓRUNS"},
    "A2-414": {"comarca": "Curiúva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-415": {"comarca": "Dois Vizinhos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-416": {"comarca": "Engenheiro Beltrão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-417": {"comarca": "Faxinai", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-418": {"comarca": "Fazenda Rio Grande", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-419": {"comarca": "Formosa Do Oeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-420": {"comarca": "Foz Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-421": {"comarca": "Francisco Beltrão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-422": {"comarca": "Goioerê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-423": {"comarca": "Grandes Rios", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-424": {"comarca": "Guaíra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-425": {"comarca": "Guaraniaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-426": {"comarca": "Guarapuava", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-427": {"comarca": "Guaratuba", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-428": {"comarca": "lbaiti", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-429": {"comarca": "lbiporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-430": {"comarca": "lcaraíma", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-431": {"comarca": "lmbituva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-432": {"comarca": "lpiranga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-433": {"comarca": "lporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-434": {"comarca": "lrati", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-435": {"comarca": "lretama", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-436": {"comarca": "lvaiporã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-437": {"comarca": "Jaca rezinho", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-438": {"comarca": "Jaguapitã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-439": {"comarca": "Jagua riaíva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-440": {"comarca": "Jandaia Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-441": {"comarca": "Joaquim Távora", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-442": {"comarca": "Lapa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-443": {"comarca": "Laranjeiras Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-444": {"comarca": "Loanda", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-445": {"comarca": "Londrina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-446": {"comarca": "Mallet", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-447": {"comarca": "Mambo rê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-448": {"comarca": "Mandaguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-449": {"comarca": "Mandaguari", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-450": {"comarca": "Mangueirinha", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-451": {"comarca": "Manoel Ribas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-452": {"comarca": "Marechal Cândido Rondon", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-453": {"comarca": "Marialva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-454": {"comarca": "Marilândia Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-455": {"comarca": "Maringá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-456": {"comarca": "Marmeleiro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-457": {"comarca": "Matelândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-458": {"comarca": "Matinhos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-459": {"comarca": "Medianeira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-460": {"comarca": "Marretes", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-461": {"comarca": "Nova Aurora", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-462": {"comarca": "Nova Esperança", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-463": {"comarca": "Nova Fátima", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-464": {"comarca": "Nova Londrina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-465": {"comarca": "Ortigueira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-466": {"comarca": "Paiçandu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-467": {"comarca": "Palmas", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-468": {"comarca": "Palmeira", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-469": {"comarca": "Palmital", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-470": {"comarca": "Palatina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-471": {"comarca": "Paraíso Do Norte", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-472": {"comarca": "Paranacity", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-473": {"comarca": "Paranaguá", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-474": {"comarca": "Paranavaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-475": {"comarca": "Pato Branco", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-476": {"comarca": "Peabiru", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-477": {"comarca": "Pérola", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-478": {"comarca": "Pinhais", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-479": {"comarca": "Pinhão", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-480": {"comarca": "Piraí Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-481": {"comarca": "Piraquara", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-482": {"comarca": "Pitanga", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-483": {"comarca": "Ponta Grossa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-484": {"comarca": "Pontal Do Paraná", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-485": {"comarca": "Porecatu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-486": {"comarca": "Primeiro De Maio", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-487": {"comarca": "Prudentópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-488": {"comarca": "Quatro Barras", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-489": {"comarca": "Quedas Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-490": {"comarca": "Realeza", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-491": {"comarca": "Rebouças", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-492": {"comarca": "Reserva", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-493": {"comarca": "Ribeirão Claro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-494": {"comarca": "Ribeirão Do Pinhal", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-495": {"comarca": "Rio Branco Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-496": {"comarca": "Rio Negro", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-497": {"comarca": "Rolândia", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-498": {"comarca": "Salto Do Lontra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-499": {"comarca": "Santa Fé", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-500": {"comarca": "Santa Helena", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-501": {"comarca": "Santa Isabel Do lvaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-502": {"comarca": "Santa Mariana", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-503": {"comarca": "Santo Antônio Da Platina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-504": {"comarca": "Santo Antônio Do Sudoeste", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-505": {"comarca": "São Jerônimo Da Serra", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-506": {"comarca": "São João", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-507": {"comarca": "São João Do lvaí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-508": {"comarca": "São João Do Triunfo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-509": {"comarca": "São José Dos Pinhais", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-510": {"comarca": "São Mateus Do Sul", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-511": {"comarca": "São Miguel Do Iguaçu", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-512": {"comarca": "Sarandi", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-513": {"comarca": "Sengés", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-514": {"comarca": "Sertanópolis", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-515": {"comarca": "Siqueira Campos", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-516": {"comarca": "Teixeira Soares", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-517": {"comarca": "Telêmaco Borba", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-518": {"comarca": "Terra Boa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-519": {"comarca": "Terra Rica", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-520": {"comarca": "Terra Roxa", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-521": {"comarca": "Tibagi", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-522": {"comarca": "Toledo", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-523": {"comarca": "Tomazina", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-524": {"comarca": "Ubiratã", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-525": {"comarca": "Umuarama", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-526": {"comarca": "União Da Vitória", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-527": {"comarca": "Uraí", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-528": {"comarca": "Wenceslau Braz", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
    "A2-529": {"comarca": "Xambrê", "unidade": "SECRETARIA DA DIREÇÃO DO FÓRUM"},
}