"""
Dados dos Anexos do Edital n 01/2026 - TJPR
"""

# =============================================================================
# ANEXO I - Vagas com deficit
# Formato: "CODIGO": {"comarca": "...", "unidade": "...", "quantidade": N}
# =============================================================================

ANEXO_I = {
    "A1-001": {"comarca": "Almirante Tamandaré", "unidade": "1ª VARA CRIMINAL", "quantidade": 1},
    "A1-002": {"comarca": "Almirante Tamandaré", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-003": {"comarca": "Almirante Tamandaré", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-004": {"comarca": "Alto Paraná", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-005": {"comarca": "Alto Piquiri", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-006": {"comarca": "Altônia", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-007": {"comarca": "Ampére", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-008": {"comarca": "Andirá", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-009": {"comarca": "Antonina", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-010": {"comarca": "Antonina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-011": {"comarca": "Arapongas", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-012": {"comarca": "Arapongas", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-013": {"comarca": "Arapongas", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-014": {"comarca": "Arapongas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 3},
    "A1-015": {"comarca": "Arapongas", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-016": {"comarca": "Araucária", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-017": {"comarca": "Araucária", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-018": {"comarca": "Araucária", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-019": {"comarca": "Assaí", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-020": {"comarca": "Assis Chateaubriand", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-021": {"comarca": "Barbosa Ferraz", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-022": {"comarca": "Barracão", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-023": {"comarca": "Bela Vista do Paraíso", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-024": {"comarca": "Bocaiúva do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-025": {"comarca": "Bocaiúva do Sul", "unidade": "VARA CÍVEL (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 1},
    "A1-026": {"comarca": "Bocaiúva do Sul", "unidade": "OFÍCIO DISTRIBUIDOR (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 1},
    "A1-027": {"comarca": "Cambará", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-028": {"comarca": "Campina da Lagoa", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-029": {"comarca": "Campina Grande do Sul", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA E DA INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-030": {"comarca": "Campo Largo", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-031": {"comarca": "Campo Largo", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-032": {"comarca": "Campo Largo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-033": {"comarca": "Campo Largo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-034": {"comarca": "Cândido de Abreu", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-035": {"comarca": "Capanema", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-036": {"comarca": "Capitão Leônidas Marques", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-037": {"comarca": "Cascavel", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-038": {"comarca": "Cascavel", "unidade": "3ª VARA CRIMINAL", "quantidade": 2},
    "A1-039": {"comarca": "Cascavel", "unidade": "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-040": {"comarca": "Cascavel", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 3},
    "A1-041": {"comarca": "Cascavel", "unidade": "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-042": {"comarca": "Castro", "unidade": "VARA CRIMINAL", "quantidade": 6},
    "A1-043": {"comarca": "Castro", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-044": {"comarca": "Castro", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-045": {"comarca": "Catanduvas", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-046": {"comarca": "Chopinzinho", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-047": {"comarca": "Cianorte", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 3},
    "A1-048": {"comarca": "Cidade Gaúcha", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-049": {"comarca": "Clevelândia", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-050": {"comarca": "Colombo", "unidade": "2ª VARA CÍVEL", "quantidade": 3},
    "A1-051": {"comarca": "Colombo", "unidade": "1ª VARA CRIMINAL", "quantidade": 4},
    "A1-052": {"comarca": "Colombo", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-053": {"comarca": "Colombo", "unidade": "VARA DA INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-054": {"comarca": "Colombo", "unidade": "VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 2},
    "A1-055": {"comarca": "Colombo", "unidade": "VARA DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-056": {"comarca": "Colorado", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-057": {"comarca": "Congonhinhas", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-058": {"comarca": "Corbélia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-059": {"comarca": "Cornélio Procópio", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-060": {"comarca": "Cornélio Procópio", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-061": {"comarca": "Coronel Vivida", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-062": {"comarca": "Curitiba", "unidade": "3ª VARA CÍVEL", "quantidade": 1},
    "A1-063": {"comarca": "Curitiba", "unidade": "23ª VARA CÍVEL", "quantidade": 1},
    "A1-064": {"comarca": "Curitiba", "unidade": "24ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 1},
    "A1-065": {"comarca": "Curitiba", "unidade": "2ª VARA DE FAMÍLIA (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 4},
    "A1-066": {"comarca": "Curitiba", "unidade": "4ª VARA DE FAMÍLIA (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 4},
    "A1-067": {"comarca": "Curitiba", "unidade": "VARA DA INFÂNCIA E DA JUVENTUDE E ADOÇÃO", "quantidade": 2},
    "A1-068": {"comarca": "Curitiba", "unidade": "1ª VARA CRIMINAL", "quantidade": 1},
    "A1-069": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO PINHEIRINHO DE CURITIBA", "quantidade": 1},
    "A1-070": {"comarca": "Curitiba", "unidade": "9ª VARA CRIMINAL", "quantidade": 1},
    "A1-071": {"comarca": "Curitiba", "unidade": "1ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI", "quantidade": 1},
    "A1-072": {"comarca": "Curitiba", "unidade": "VARA DE DELITOS DE TRÂNSITO", "quantidade": 1},
    "A1-073": {"comarca": "Curitiba", "unidade": "13º JUIZADO ESPECIAL CÍVEL E CRIMINAL", "quantidade": 1},
    "A1-074": {"comarca": "Curitiba", "unidade": "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DA CIDADE INDUSTRIAL DE CURITIBA", "quantidade": 1},
    "A1-075": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-076": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS ESPECIAIS DA FAZENDA PÚBLICA", "quantidade": 5},
    "A1-077": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER", "quantidade": 7},
    "A1-078": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS ESTADUAIS", "quantidade": 2},
    "A1-079": {"comarca": "Curitiba", "unidade": "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS MUNICIPAIS", "quantidade": 3},
    "A1-080": {"comarca": "Curiúva", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-081": {"comarca": "Dois Vizinhos", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 5},
    "A1-082": {"comarca": "Engenheiro Beltrão", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-083": {"comarca": "Faxinal", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-084": {"comarca": "Fazenda Rio Grande", "unidade": "VARA CRIMINAL", "quantidade": 6},
    "A1-085": {"comarca": "Fazenda Rio Grande", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 3},
    "A1-086": {"comarca": "Fazenda Rio Grande", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-087": {"comarca": "Fazenda Rio Grande", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-088": {"comarca": "Formosa do Oeste", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-089": {"comarca": "Foz do Iguaçu", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 3},
    "A1-090": {"comarca": "Foz do Iguaçu", "unidade": "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-091": {"comarca": "Francisco Beltrão", "unidade": "1ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-092": {"comarca": "Francisco Beltrão", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-093": {"comarca": "Francisco Beltrão", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 3},
    "A1-094": {"comarca": "Goioerê", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-095": {"comarca": "Goioerê", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-096": {"comarca": "Grandes Rios", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-097": {"comarca": "Guaíra", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-098": {"comarca": "Guaraniaçu", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-099": {"comarca": "Ibaiti", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-100": {"comarca": "Ibiporã", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-101": {"comarca": "Icaraíma", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-102": {"comarca": "Imbituva", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-103": {"comarca": "Iporã", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-104": {"comarca": "Irati", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-105": {"comarca": "Irati", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-106": {"comarca": "Irati", "unidade": "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS", "quantidade": 3},
    "A1-107": {"comarca": "Iretama", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-108": {"comarca": "Ivaiporã", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-109": {"comarca": "Ivaiporã", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-110": {"comarca": "Jacarezinho", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-111": {"comarca": "Jaguapitã", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-112": {"comarca": "Jaguariaíva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-113": {"comarca": "Joaquim Távora", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-114": {"comarca": "Laranjeiras do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-115": {"comarca": "Londrina", "unidade": "3ª VARA DE FAMÍLIA", "quantidade": 1},
    "A1-116": {"comarca": "Londrina", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 1},
    "A1-117": {"comarca": "Londrina", "unidade": "VARA DE SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-118": {"comarca": "Londrina", "unidade": "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 1},
    "A1-119": {"comarca": "Londrina", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 2},
    "A1-120": {"comarca": "Londrina", "unidade": "1ª VARA DE FAMÍLIA (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 7},
    "A1-121": {"comarca": "Mamborê", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-122": {"comarca": "Mandaguari", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-123": {"comarca": "Mangueirinha", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-124": {"comarca": "Manoel Ribas", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-125": {"comarca": "Marechal Cândido Rondon", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-126": {"comarca": "Marialva", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-127": {"comarca": "Marilândia do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-128": {"comarca": "Maringá", "unidade": "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO", "quantidade": 2},
    "A1-129": {"comarca": "Matelândia", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-130": {"comarca": "Medianeira", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 7},
    "A1-131": {"comarca": "Nova Aurora", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-132": {"comarca": "Nova Esperança", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-133": {"comarca": "Nova Esperança", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-134": {"comarca": "Nova Fátima", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-135": {"comarca": "Ortigueira", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-136": {"comarca": "Paiçandu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-137": {"comarca": "Palmas", "unidade": "VARA CRIMINAL E DA INFÂNCIA E JUVENTUDE", "quantidade": 4},
    "A1-138": {"comarca": "Palmas", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-139": {"comarca": "Palmeira", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-140": {"comarca": "Palmital", "unidade": "OFÍCIO DISTRIBUIDOR (EM PROCESSO DE ESTATIZAÇÃO)", "quantidade": 3},
    "A1-141": {"comarca": "Palotina", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-142": {"comarca": "Paraíso do Norte", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-143": {"comarca": "Paranacity", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-144": {"comarca": "Paranaguá", "unidade": "1ª VARA CÍVEL", "quantidade": 1},
    "A1-145": {"comarca": "Paranaguá", "unidade": "2ª VARA CÍVEL", "quantidade": 5},
    "A1-146": {"comarca": "Paranaguá", "unidade": "VARA DE FAMÍLIA E SUCESSÕES", "quantidade": 2},
    "A1-147": {"comarca": "Paranaguá", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-148": {"comarca": "Paranaguá", "unidade": "2ª VARA CRIMINAL", "quantidade": 2},
    "A1-149": {"comarca": "Paranaguá", "unidade": "VARA DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-150": {"comarca": "Peabiru", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-151": {"comarca": "Pérola", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-152": {"comarca": "Pinhais", "unidade": "VARA CRIMINAL", "quantidade": 1},
    "A1-153": {"comarca": "Pinhão", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-154": {"comarca": "Piraí do Sul", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-155": {"comarca": "Piraquara", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 4},
    "A1-156": {"comarca": "Piraquara", "unidade": "VARA CRIMINAL", "quantidade": 5},
    "A1-157": {"comarca": "Piraquara", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-158": {"comarca": "Piraquara", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-159": {"comarca": "Pitanga", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-160": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CÍVEL E EMPRESARIAL REGIONAL", "quantidade": 2},
    "A1-161": {"comarca": "Ponta Grossa", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-162": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 2},
    "A1-163": {"comarca": "Ponta Grossa", "unidade": "3ª VARA CRIMINAL", "quantidade": 2},
    "A1-164": {"comarca": "Ponta Grossa", "unidade": "VARA DA INFÂNCIA E JUVENTUDE", "quantidade": 2},
    "A1-165": {"comarca": "Ponta Grossa", "unidade": "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS", "quantidade": 1},
    "A1-166": {"comarca": "Ponta Grossa", "unidade": "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-167": {"comarca": "Pontal do Paraná", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-168": {"comarca": "Porecatu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 1},
    "A1-169": {"comarca": "Primeiro de Maio", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-170": {"comarca": "Quatro Barras", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-171": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA", "quantidade": 4},
    "A1-172": {"comarca": "Quedas do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-173": {"comarca": "Realeza", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-174": {"comarca": "Reserva", "unidade": "JUÍZO ÚNICO", "quantidade": 4},
    "A1-175": {"comarca": "Ribeirão do Pinhal", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-176": {"comarca": "Rio Branco do Sul", "unidade": "VARA CRIMINAL E INFÂNCIA E JUVENTUDE", "quantidade": 1},
    "A1-177": {"comarca": "Salto do Lontra", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-178": {"comarca": "Santa Fé", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-179": {"comarca": "Santa Helena", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-180": {"comarca": "Santa Isabel do Ivaí", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-181": {"comarca": "Santo Antônio da Platina", "unidade": "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES", "quantidade": 1},
    "A1-182": {"comarca": "Santo Antônio da Platina", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 2},
    "A1-183": {"comarca": "Santo Antônio do Sudoeste", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-184": {"comarca": "São Jerônimo da Serra", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-185": {"comarca": "São João", "unidade": "JUÍZO ÚNICO", "quantidade": 5},
    "A1-186": {"comarca": "São João do Triunfo", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-187": {"comarca": "São José dos Pinhais", "unidade": "2ª VARA CRIMINAL", "quantidade": 1},
    "A1-188": {"comarca": "São José dos Pinhais", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-189": {"comarca": "São José dos Pinhais", "unidade": "VARA DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-190": {"comarca": "São José dos Pinhais", "unidade": "VARA DESCENTRALIZADA DO AFONSO PENA", "quantidade": 2},
    "A1-191": {"comarca": "São José dos Pinhais", "unidade": "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS", "quantidade": 1},
    "A1-192": {"comarca": "São Mateus do Sul", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 3},
    "A1-193": {"comarca": "São Miguel do Iguaçu", "unidade": "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL", "quantidade": 2},
    "A1-194": {"comarca": "Sarandi", "unidade": "2ª VARA CRIMINAL", "quantidade": 1},
    "A1-195": {"comarca": "Sertanópolis", "unidade": "JUÍZO ÚNICO", "quantidade": 1},
    "A1-196": {"comarca": "Siqueira Campos", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-197": {"comarca": "Teixeira Soares", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-198": {"comarca": "Telêmaco Borba", "unidade": "VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-199": {"comarca": "Telêmaco Borba", "unidade": "VARA CRIMINAL", "quantidade": 2},
    "A1-200": {"comarca": "Telêmaco Borba", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 2},
    "A1-201": {"comarca": "Telêmaco Borba", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-202": {"comarca": "Terra Rica", "unidade": "JUÍZO ÚNICO", "quantidade": 5},
    "A1-203": {"comarca": "Terra Roxa", "unidade": "JUÍZO ÚNICO", "quantidade": 3},
    "A1-204": {"comarca": "Tibagi", "unidade": "JUÍZO ÚNICO", "quantidade": 5},
    "A1-205": {"comarca": "Toledo", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-206": {"comarca": "Toledo", "unidade": "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-207": {"comarca": "Tomazina", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
    "A1-208": {"comarca": "Umuarama", "unidade": "1ª VARA CRIMINAL", "quantidade": 2},
    "A1-209": {"comarca": "Umuarama", "unidade": "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL", "quantidade": 1},
    "A1-210": {"comarca": "União da Vitória", "unidade": "2ª VARA CÍVEL E DA FAZENDA PÚBLICA", "quantidade": 1},
    "A1-211": {"comarca": "União da Vitória", "unidade": "2ª VARA CRIMINAL", "quantidade": 3},
    "A1-212": {"comarca": "Wenceslau Braz", "unidade": "JUÍZO ÚNICO", "quantidade": 2},
}