"""
Script para adicionar unidades faltantes ao Anexo II do Edital 01/2026
Baseado no arquivo anexoii-faltantes.pdf
"""

# Unidades faltantes extraídas do PDF
UNIDADES_FALTANTES = [
    # Página 1 - Curitiba
    ("Curitiba", "7ª VARA DE FAMÍLIA"),
    ("Curitiba", "1ª VARA DE SUCESSÕES"),
    ("Curitiba", "VARA DE REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Curitiba", "VARA DA INFÂNCIA E DA JUVENTUDE E ADOÇÃO"),
    ("Curitiba", "2ª VARA DE SUCESSÕES"),
    ("Curitiba", "VARA DE ADOLESCENTES EM CONFLITO COM A LEI"),
    ("Curitiba", "1ª VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Curitiba", "1ª VARA CRIMINAL"),
    ("Curitiba", "2ª VARA CRIMINAL"),
    ("Curitiba", "3ª VARA CRIMINAL"),
    ("Curitiba", "4ª VARA CRIMINAL"),
    ("Curitiba", "CENTRAL DE GARANTIAS ESPECIALIZADA"),
    ("Curitiba", "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO PINHEIRINHO"),
    ("Curitiba", "7ª VARA CRIMINAL"),
    ("Curitiba", "8ª VARA CRIMINAL"),
    ("Curitiba", "9ª VARA CRIMINAL"),
    ("Curitiba", "10ª VARA CRIMINAL"),
    ("Curitiba", "2ª VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Curitiba", "12ª VARA CRIMINAL"),
    ("Curitiba", "13ª VARA CRIMINAL"),
    ("Curitiba", "1ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI"),
    ("Curitiba", "2ª VARA PRIVATIVA DO TRIBUNAL DO JÚRI"),
    ("Curitiba", "VARA DE DELITOS DE TRÂNSITO"),
    ("Curitiba", "3º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER - CASA DA MULHER BRASILEIRA"),
    ("Curitiba", "VARA DA AUDITORIA DA JUSTIÇA MILITAR"),
    ("Curitiba", "1º JUIZADO ESPECIAL CÍVEL - MATÉRIA BANCÁRIA"),
    ("Curitiba", "JUIZADO ESPECIAL PUC-CAJURU"),
    ("Curitiba", "3º JUIZADO ESPECIAL CÍVEL - TELECOMUNICAÇÕES"),
    ("Curitiba", "5º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Curitiba", "6º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Curitiba", "8º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Curitiba", "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO BAIRRO NOVO (SÍTIO CERCADO)"),
    ("Curitiba", "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DO BOQUEIRÃO"),
    ("Curitiba", "11º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Curitiba", "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DE SANTA FELICIDADE"),
    ("Curitiba", "13º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),

    # Página 2 - Curitiba (continuação)
    ("Curitiba", "14º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Curitiba", "SECRETARIA UNIFICADA DA 1ª E 2ª VARAS DESCENTRALIZADAS DA CIDADE INDUSTRIAL"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DA FAZENDA PÚBLICA"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS ESPECIAIS DA FAZENDA PÚBLICA"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DOS JUIZADOS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS ESTADUAIS"),
    ("Curitiba", "SECRETARIA ESPECIALIZADA EM MOVIMENTAÇÕES PROCESSUAIS DAS VARAS DE EXECUÇÕES FISCAIS MUNICIPAIS"),
    ("Curiúva", "JUÍZO ÚNICO"),
    ("Dois Vizinhos", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Engenheiro Beltrão", "JUÍZO ÚNICO"),
    ("Faxinal", "JUÍZO ÚNICO"),
    ("Fazenda Rio Grande", "VARA CRIMINAL"),
    ("Fazenda Rio Grande", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Fazenda Rio Grande", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Fazenda Rio Grande", "2ª VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Formosa do Oeste", "JUÍZO ÚNICO"),
    ("Foz do Iguaçu", "1ª VARA CRIMINAL"),
    ("Foz do Iguaçu", "2ª VARA CRIMINAL"),
    ("Foz do Iguaçu", "3ª VARA CRIMINAL"),
    ("Foz do Iguaçu", "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Foz do Iguaçu", "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"),
    ("Foz do Iguaçu", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("Foz do Iguaçu", "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"),
    ("Foz do Iguaçu", "1ª VARA DA FAZENDA PÚBLICA"),
    ("Foz do Iguaçu", "2ª VARA DA FAZENDA PÚBLICA"),
    ("Foz do Iguaçu", "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Foz do Iguaçu", "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Foz do Iguaçu", "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),

    # Página 3 - Francisco Beltrão, Goioerê, etc.
    ("Francisco Beltrão", "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Francisco Beltrão", "VARA CRIMINAL"),
    ("Francisco Beltrão", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Francisco Beltrão", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Francisco Beltrão", "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"),
    ("Goioerê", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Goioerê", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Grandes Rios", "JUÍZO ÚNICO"),
    ("Guaíra", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Guaíra", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Guaraniaçu", "JUÍZO ÚNICO"),
    ("Guarapuava", "1ª VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Guarapuava", "3ª VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Guarapuava", "1ª VARA CRIMINAL"),
    ("Guarapuava", "2ª VARA CRIMINAL"),
    ("Guarapuava", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("Guarapuava", "VARA DE FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Guarapuava", "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"),
    ("Guarapuava", "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Guarapuava", "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Guarapuava", "3ª VARA CRIMINAL"),
    ("Guaratuba", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Ibaiti", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Ibiporã", "VARA CRIMINAL"),
    ("Ibiporã", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Ibiporã", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Icaraíma", "JUÍZO ÚNICO"),
    ("Imbituva", "JUÍZO ÚNICO"),
    ("Ipiranga", "JUÍZO ÚNICO"),
    ("Iporã", "JUÍZO ÚNICO"),

    # Página 4 - Irati, Ivaiporã, Jacarezinho, etc.
    ("Irati", "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"),
    ("Irati", "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E VARA DE FAMÍLIA E SUCESSÕES"),
    ("Irati", "SECRETARIA ESPECIALIZADA DE MOVIMENTAÇÃO PROCESSUAL DAS VARAS CÍVEIS"),
    ("Iretama", "JUÍZO ÚNICO"),
    ("Ivaiporã", "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"),
    ("Ivaiporã", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Jacarezinho", "VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Jacarezinho", "VARA CRIMINAL"),
    ("Jacarezinho", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Jacarezinho", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Jaguapitã", "JUÍZO ÚNICO"),
    ("Jaguariaíva", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Jandaia do Sul", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Jandaia do Sul", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Joaquim Távora", "JUÍZO ÚNICO"),
    ("Lapa", "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"),
    ("Lapa", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Laranjeiras do Sul", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Loanda", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Londrina", "VARA PRIVATIVA DO TRIBUNAL DO JÚRI"),
    ("Londrina", "2ª VARA CRIMINAL"),
    ("Londrina", "3ª VARA CRIMINAL"),
    ("Londrina", "4ª VARA CRIMINAL"),
    ("Londrina", "5ª VARA CRIMINAL"),
    ("Londrina", "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Londrina", "3ª VARA DE FAMÍLIA"),
    ("Londrina", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("Londrina", "VARA DE SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Londrina", "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"),

    # Página 5 - Londrina (continuação)
    ("Londrina", "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Londrina", "1º JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Londrina", "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Londrina", "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Londrina", "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Londrina", "5º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Londrina", "6º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Londrina", "VARA DA FAZENDA PÚBLICA"),
    ("Londrina", "11ª VARA CÍVEL E EMPRESARIAL REGIONAL"),
    ("Londrina", "1ª VARA DE EXECUÇÕES FISCAIS"),
    ("Londrina", "2ª VARA DE EXECUÇÕES FISCAIS"),
    ("Mallet", "JUÍZO ÚNICO"),
    ("Mamborê", "JUÍZO ÚNICO"),
    ("Mandaguaçu", "JUÍZO ÚNICO"),
    ("Mandaguari", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Mangueirinha", "JUÍZO ÚNICO"),
    ("Manoel Ribas", "JUÍZO ÚNICO"),
    ("Marechal Cândido Rondon", "VARA CRIMINAL"),
    ("Marechal Cândido Rondon", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Marechal Cândido Rondon", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Marialva", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Marilândia do Sul", "JUÍZO ÚNICO"),
    ("Maringá", "3ª VARA CÍVEL E EMPRESARIAL REGIONAL"),
    ("Maringá", "4ª VARA CÍVEL"),
    ("Maringá", "7ª VARA CÍVEL"),
    ("Maringá", "1ª VARA CRIMINAL"),
    ("Maringá", "2ª VARA CRIMINAL"),
    ("Maringá", "3ª VARA CRIMINAL"),
    ("Maringá", "4ª VARA CRIMINAL"),
    ("Maringá", "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Maringá", "1ª VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Maringá", "2ª VARA DE FAMÍLIA E SUCESSÕES E ACIDENTES DO TRABALHO"),
    ("Maringá", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("Maringá", "1ª VARA DA FAZENDA PÚBLICA"),

    # Página 6 - Maringá (continuação)
    ("Maringá", "2ª VARA DA FAZENDA PÚBLICA"),
    ("Maringá", "VARA DE EXECUÇÕES PENAIS, MEDIDAS ALTERNATIVAS E CORREGEDORIA DOS PRESÍDIOS"),
    ("Maringá", "5º JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Maringá", "1º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Maringá", "2º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Maringá", "3º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Maringá", "4º JUIZADO ESPECIAL CÍVEL E CRIMINAL"),
    ("Marmeleiro", "JUÍZO ÚNICO"),
    ("Matelândia", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Matinhos", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Medianeira", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Morretes", "JUÍZO ÚNICO"),
    ("Nova Aurora", "JUÍZO ÚNICO"),
    ("Nova Esperança", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Nova Esperança", "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"),
    ("Nova Esperança", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Nova Fátima", "JUÍZO ÚNICO"),
    ("Nova Londrina", "JUÍZO ÚNICO"),
    ("Ortigueira", "JUÍZO ÚNICO"),
    ("Paiçandu", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Paiçandu", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Palmas", "VARA CRIMINAL E DA INFÂNCIA E JUVENTUDE"),
    ("Palmas", "VARA DE FAMÍLIA E SUCESSÕES, JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Palmeira", "JUÍZO ÚNICO"),
    ("Palmital", "JUÍZO ÚNICO"),
    ("Palotina", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Paraíso do Norte", "JUÍZO ÚNICO"),
    ("Paranacity", "JUÍZO ÚNICO"),
    ("Paranaguá", "1ª VARA CÍVEL"),
    ("Paranaguá", "2ª VARA CÍVEL"),
    ("Paranaguá", "VARA DE FAMÍLIA E SUCESSÕES"),
    ("Paranaguá", "1ª VARA CRIMINAL"),
    ("Paranaguá", "2ª VARA CRIMINAL"),

    # Página 7 - Paranaguá (continuação), Paranavaí, Pato Branco, etc.
    ("Paranaguá", "VARA DA INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Paranaguá", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Paranaguá", "VARA DA FAZENDA PÚBLICA"),
    ("Paranavaí", "1ª VARA CRIMINAL"),
    ("Paranavaí", "2ª VARA CRIMINAL"),
    ("Paranavaí", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Paranavaí", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Pato Branco", "VARA CRIMINAL"),
    ("Pato Branco", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Pato Branco", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Peabiru", "JUÍZO ÚNICO"),
    ("Pérola", "JUÍZO ÚNICO"),
    ("Pinhais", "VARA CRIMINAL"),
    ("Pinhais", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Pinhais", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Pinhão", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Pinhão", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Piraí do Sul", "JUÍZO ÚNICO"),
    ("Piraquara", "VARA CÍVEL E DA FAZENDA PÚBLICA"),
    ("Piraquara", "VARA CRIMINAL"),
    ("Piraquara", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Piraquara", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Pitanga", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Ponta Grossa", "1ª VARA CÍVEL E EMPRESARIAL REGIONAL"),
    ("Ponta Grossa", "1ª VARA CRIMINAL"),
    ("Ponta Grossa", "2º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Ponta Grossa", "3ª VARA CRIMINAL"),
    ("Ponta Grossa", "1º JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("Ponta Grossa", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("Ponta Grossa", "VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS"),

    # Página 8 - Ponta Grossa (continuação), Pontal do Paraná, etc.
    ("Ponta Grossa", "1ª VARA DA FAZENDA PÚBLICA"),
    ("Ponta Grossa", "2ª VARA DA FAZENDA PÚBLICA"),
    ("Ponta Grossa", "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Ponta Grossa", "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Ponta Grossa", "3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Pontal do Paraná", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Pontal do Paraná", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL CRIMINAL"),
    ("Porecatu", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Porecatu", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Primeiro de Maio", "JUÍZO ÚNICO"),
    ("Prudentópolis", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Prudentópolis", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Quatro Barras", "JUÍZO ÚNICO"),
    ("Quedas do Iguaçu", "VARA CÍVEL, DA FAZENDA PÚBLICA, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL, JUIZADO ESPECIAL CÍVEL E JUIZADO ESPECIAL DA FAZENDA PÚBLICA"),
    ("Quedas do Iguaçu", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Realeza", "JUÍZO ÚNICO"),
    ("Rebouças", "JUÍZO ÚNICO"),
    ("Reserva", "JUÍZO ÚNICO"),
    ("Ribeirão Claro", "JUÍZO ÚNICO"),
    ("Ribeirão do Pinhal", "JUÍZO ÚNICO"),
    ("Rio Branco do Sul", "VARA CRIMINAL E INFÂNCIA E JUVENTUDE"),
    ("Rio Branco do Sul", "JUIZADO ESPECIAL CÍVEL, CRIMINAL, DA FAZENDA PÚBLICA E FAMÍLIA E SUCESSÕES"),
    ("Rio Negro", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Rolândia", "VARA CRIMINAL E JUIZADO ESPECIAL CRIMINAL"),
    ("Rolândia", "VARA DA INFÂNCIA E JUVENTUDE, FAMÍLIA E SUCESSÕES, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("Rolândia", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Salto do Lontra", "JUÍZO ÚNICO"),
    ("Santa Fé", "JUÍZO ÚNICO"),

    # Página 9 - Santa Helena, Santo Antônio da Platina, São José dos Pinhais, etc.
    ("Santa Helena", "JUÍZO ÚNICO"),
    ("Santa Isabel do Ivaí", "JUÍZO ÚNICO"),
    ("Santa Mariana", "JUÍZO ÚNICO"),
    ("Santo Antônio da Platina", "VARA CRIMINAL, INFÂNCIA E JUVENTUDE E FAMÍLIA E SUCESSÕES"),
    ("Santo Antônio da Platina", "JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("Santo Antônio do Sudoeste", "JUÍZO ÚNICO"),
    ("São Jerônimo da Serra", "JUÍZO ÚNICO"),
    ("São João", "JUÍZO ÚNICO"),
    ("São João do Ivaí", "JUÍZO ÚNICO"),
    ("São João do Triunfo", "JUÍZO ÚNICO"),
    ("São José dos Pinhais", "3ª VARA CÍVEL"),
    ("São José dos Pinhais", "1ª VARA CRIMINAL"),
    ("São José dos Pinhais", "2ª VARA CRIMINAL"),
    ("São José dos Pinhais", "VARA DA INFÂNCIA E JUVENTUDE"),
    ("São José dos Pinhais", "VARA DE FAMÍLIA E SUCESSÕES, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
    ("São José dos Pinhais", "VARA DA FAZENDA PÚBLICA"),
    ("São José dos Pinhais", "1º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("São José dos Pinhais", "2º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA"),
    ("São José dos Pinhais", "VARA DESCENTRALIZADA DO AFONSO PENA"),
    ("São José dos Pinhais", "JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER, VARA DE CRIMES CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS"),
    ("São Mateus do Sul", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("São Miguel do Iguaçu", "VARA CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE E JUIZADO ESPECIAL CRIMINAL"),
    ("Sarandi", "1ª VARA CRIMINAL"),
    ("Sarandi", "2ª VARA CRIMINAL"),
    ("Sarandi", "VARA DE FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL"),
]


def adicionar_unidades_faltantes():
    """Adiciona unidades faltantes ao ANEXO_II"""

    # Ler arquivo atual
    with open('data.py', 'r', encoding='utf-8') as f:
        conteudo = f.read()

    # Encontrar o maior código A2 atual
    import re
    codigos = re.findall(r'"A2-(\d+)"', conteudo)
    if codigos:
        ultimo_codigo = max(int(c) for c in codigos)
    else:
        ultimo_codigo = 0

    print(f"Último código A2 atual: A2-{ultimo_codigo:03d}")
    print(f"Unidades a adicionar: {len(UNIDADES_FALTANTES)}")

    # Gerar novas entradas
    novas_entradas = []
    contador = ultimo_codigo + 1

    for comarca, unidade in UNIDADES_FALTANTES:
        codigo = f"A2-{contador:03d}"
        entrada = f'    "{codigo}": {{"comarca": "{comarca}", "unidade": "{unidade}"}},'
        novas_entradas.append(entrada)
        contador += 1

    print(f"Novos códigos: A2-{ultimo_codigo+1:03d} até A2-{contador-1:03d}")

    # Encontrar onde inserir (antes do último "}")
    # O ANEXO_II termina com "}\n" no final do arquivo
    pos_fim_anexo2 = conteudo.rfind('}')

    # Inserir novas entradas
    novo_conteudo = conteudo[:pos_fim_anexo2] + '\n' + '\n'.join(novas_entradas) + '\n' + conteudo[pos_fim_anexo2:]

    # Salvar arquivo atualizado
    with open('data.py', 'w', encoding='utf-8') as f:
        f.write(novo_conteudo)

    print(f"\nArquivo data.py atualizado!")
    print(f"Total de unidades adicionadas: {len(UNIDADES_FALTANTES)}")
    print(f"Novo total esperado: {ultimo_codigo + len(UNIDADES_FALTANTES)} unidades no ANEXO_II")


if __name__ == '__main__':
    adicionar_unidades_faltantes()
